### ISSUE TITLE
Add check-in test that detects if all dependencies are available as conda packages

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1003]
When building the featuretools package on conda-forge, all required dependencies and testing dependencies must also be available on conda.  Sometimes we noice that the version we require for a dependency isn't available on conda yet, or a package is missing on conda, but this happens when preparing a release, not when the unavailable requirement was added.  If we could add a test that compared the requirements with the available packages on conda-forge, we could catch these issues earlier in the process

**Comment by gsheni** [comment]
If this becomes a problem, we will reopen
