### ISSUE TITLE
Support for NLP primitives for Dask

### ISSUE THREAD

**Issue by jrdzha** [alteryx/featuretools#1039]
### Support for NLP primitives for Dask

`ValueError: Selected primitives are incompatible with Dask EntitySets: diversity_score, lsa, mean_characters_per_word, part_of_speech_count, polarity_score, punctuation_count, stopword_count, title_word_count, universal_sentence_encoder, upper_case_count`

#### Bug/Feature Request Description

Unable to use NLP primitives for Dask Dataframes

**Comment by thehomebrewnerd** [comment]
@jrdzha Thanks you for submitting this issue. At this time, only certain primitives are supported when using Dask Entitysets. [This section of the docs](https://docs.featuretools.com/en/stable/guides/using_dask_entitysets.html#supported-primitives) provides additional information.

We can, however, take a look at implementing support for the NLP primitives in a future release.

**Comment by jrdzha** [comment]
@thehomebrewnerd Thanks, that would be really useful to me. Is there a workaround I could use right now? Would creating an entity set for each dask partition work?

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd Thanks, that would be really useful to me. Is there a workaround I could use right now? Would creating an entity set for each dask partition work?

The specific solution depends on your exact problem and dataset. Creating an entityset for each Dask partition could be problematic if you are using aggregation primitives, as those would not aggregate properly over the various entitysets. If you are not using aggregation primitives, you could potentially create a feature matrix for each partition using the approach you describe, concating them together in the end if you needed a single feature matrix.

Depending on the size of your dataset you also may be able to work entirely in Pandas, which would allow you to use the NLP primitives.

If you need aggregation primitives you will need to partition your data into chunks such that each partition contains all the information you need for the aggregation. You can then calculate a feature matrix with a pandas entityset for each of these partitions and then stitch them back together again at the end, if needed.

I suggest you take a look at the [Improving Computational Performance](https://docs.featuretools.com/en/stable/guides/performance.html#parallel-computation-by-partitioning-data) document for some additional information.

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
