### ISSUE TITLE
[Enhancement] Generate metadata for custom variables and primitives

### ISSUE THREAD

**Issue by rohan-gt** [alteryx/featuretools#1084]
Some enhancement suggestions:
1. Add the **input_types** and **return_types** columns to `list_primitives()`
2. Add metadata from custom variables and custom primitives into `list_variable_types()` and `list_primitives()` respectively and maybe add a column called **category** having the values `'base'` and `'custom'` to distinguish them in the resulting DataFrame to track them better

**Comment by rwedge** [comment]
some overlap with #1181, linking for reference
