### ISSUE TITLE
[Bug] make_trans_primitive documentation example is not clear

### ISSUE THREAD

**Issue by rohan-gt** [alteryx/featuretools#1100]
Is the following code example detailed [here](https://docs.featuretools.com/en/stable/generated/featuretools.primitives.make_trans_primitive.html) correct?

```python
In [1]: from featuretools.primitives import make_trans_primitive

In [2]: from featuretools.variable_types import Variable, Boolean

In [3]: def pd_is_in(array, list_of_outputs=None):
   ...:     if list_of_outputs is None:
   ...:         list_of_outputs = []
   ...:     return pd.Series(array).isin(list_of_outputs)
   ...: 

In [4]: def isin_generate_name(self):
   ...:     return u"%s.isin(%s)" % (self.base_features[0].get_name(),
   ...:                              str(self.kwargs['list_of_outputs']))
   ...: 

In [5]: IsIn = make_trans_primitive(
   ...:     function=pd_is_in,
   ...:     input_types=[Variable],
   ...:     return_type=Boolean,
   ...:     name="is_in",
   ...:     description="For each value of the base feature, checks "
   ...:     "whether it is in a list that provided.",
   ...:     cls_attributes={"generate_name": isin_generate_name})
   ...: 
```

Questions:
1. How is `isin_generate_name` defined outside a class? And if that's not right, how do you configure an optional parameter to the primitive?
2. Is there a way to pass the custom primitive as a string? And if so, how do you pass the parameter `list_of_outputs`?
3. If the primitive has multiple inputs (eg. `A` and `B`), how do you configure a custom name like `A - B` for the resulting feature?

**Comment by kmax12** [comment]
the example is a bit confusion, we've discussed updating the docs to demonstrate how to define custom primitives using class (which is the same way we do it internally)

**Comment by gsheni** [comment]
@rohan-gt We have a [guide](https://featuretools.alteryx.com/en/latest/guides/advanced_custom_primitives.html) on how to define custom primitives using class. This guide should answer your questions. Let us know if it does not.
