### ISSUE TITLE
Add return values to API reference for dfs method

### ISSUE THREAD

**Issue by dsherry** [alteryx/featuretools#1117]
### Add return values to docs for dfs method
[Some code on the "What is Featuretools?" guide page](https://docs.featuretools.com/en/stable/index.html#change-target-entity), as well as [the example at the bottom of the `dfs` API reference](https://docs.featuretools.com/en/latest/generated/featuretools.dfs.html#featuretools.dfs), imply that `dfs` returns multiple values. But the API ref doesn't describe the return type(s) and behavior.

**Comment by tyler3991** [comment]
completed, closing
