### ISSUE TITLE
Is there any way to restrict the transformation feature in DFS?

### ISSUE THREAD

**Issue by zhenlingcn** [alteryx/featuretools#1124]
In real practice, I find that using transformation primitives in deep feature synthesis will produce numerous features, and that is because there are a lot of nested transformation features (such as "absolute(percentile(x))").  However, I only want to apply those transformations on original features (such as "percentile(x)"), and then only use aggregation primitive to process them. I know that there is one feasible way is that I can preprocess my datasets, and then only use featuretool to do aggregations. Nonetheless, I hope I can only use featuretool to do all of them. Thus, is there any way to restrict the transformation feature in DFS?

**Comment by tamargrey** [comment]
We actually have a PR open right now to do this (#1119). In it, we restrict transform primitives so they can't stack directly on another transform feature.

**Comment by tyler3991** [comment]
We implemented the change in #1119 , closing.
