### ISSUE TITLE
Add entity_type attribute to entities

### ISSUE THREAD

**Issue by frances-h** [alteryx/featuretools#1139]
Currently, entities do not track what type of dataframe they are based on (i.e. pandas, Dask, or Koalas). Instead, Featuretools currently uses repeated `isinstance` checks. Entities and EntitySets should be aware of their own type, and we should replace `isinstance` checks with checking the entity/entityset type.

A notable caveat is that Koalas dataframes cannot be empty. There are instances where we deserialize/serialize entitysets to act as empty metadata entitysets. These metadata entities and entitysets will need to be able to keep track of their parent's entity type even though their own dataframe is an empty pandas dataframe. Intentionally empty pandas entities must still have a pandas `entity_type`

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
