### ISSUE TITLE
Add additional compatible aggregation primitives

### ISSUE THREAD

**Issue by frances-h** [alteryx/featuretools#1142]
Currently, Koalas can only do groupby aggregations with named aggregations. Based off of [this ](https://github.com/FeatureLabs/featuretools/pull/1031#pullrequestreview-457746715) review, we could implement more compatible aggregations by using `.apply` instead of `.agg`, or by using custom aggregations through Spark. Using one of the suggested methods, we should implement Koalas compatibility with more aggregations.

**Comment by thehomebrewnerd** [comment]
Pyspark support is being dropped
