### ISSUE TITLE
Make code examples easier to copy from docs

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1172]
In some places on the docs the code looks like this:

```
In [3]: customers_df = data["customers"]

In [4]: customers_df
Out[4]: 
   customer_id zip_code           join_date date_of_birth
0            1    60091 2011-04-17 10:48:33    1994-07-18
1            2    13244 2012-04-15 23:31:04    1986-08-18
2            3    13244 2011-08-13 15:42:34    2003-11-21
3            4    60091 2011-04-08 20:08:14    2006-08-15
4            5    60091 2010-07-17 05:27:50    1984-07-28
```

Selecting the cell brings the "In [3]" parts with it

Would be more user-friendly if we could avoid this

**Comment by gsheni** [comment]
One way to do this is to switch all `rst` files to `ipynb` notebooks. We do this in the FAQ.

<img width="568" alt="Screen Shot 2020-10-02 at 11 23 29 AM" src="https://user-images.githubusercontent.com/8726321/94940622-bbaf3680-04a1-11eb-8237-5284cd146d4f.png">

**Comment by gsheni** [comment]
This has been completed
