### ISSUE TITLE
Add Python 3.9 support

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1176]
- With the release of Python 3.9, we should test our CI in an environment with Python 3.9, and make sure Featuretools supports it. 
- https://www.python.org/downloads/release/python-390/

**Comment by gsheni** [comment]
Tracking dependencies that support 3.9
- [ ] scipy
- [ ] numpy
- [ ] pandas
- [ ] tqdm
- [ ] pyyaml
- [ ] cloudpickle
- [ ] distributed
- [ ] dask[dataframe]
- [ ] psutil
- [ ] click
- [ ] pyspark
- [ ] koalas
- [ ] codecov
- [ ] matplotlib
- [ ] nbconvert
- [ ] nbsphinx
- [ ] Sphinx

**Comment by tyler3991** [comment]
#1331 will address 3.9 w/ koalas
