### ISSUE TITLE
Add descriptive categories to list_primitives()

### ISSUE THREAD

**Issue by SydneyAyx** [alteryx/featuretools#1181]
#### Feature Request Description

Currently, primitives are only categorized by if they are aggregation or transform primitives. It would be helpful if we could describe primitives by what data type they can be used on (e.g., datetime, spatial, text). 

#### Expected Output
```python
primitives = list_primitives()
primitives
```

[{name: primtive_name, description: primitive_description, type: "spatial"}, {...}, {...}]

**Comment by kmax12** [comment]
for descriptive categories, would just using the input variable types work?

**Comment by rwedge** [comment]
We could look at all input types for a primitive and get the unique input types

so primitive `Day` has `input_types = [Datetime]`, so "type" would be `Datetime`

primitive `Haversine` has `input_types = [LatLong, LatLong]` so "type" would be `LatLong`

primitive `Trend` has `input_types = [Numeric, DatetimeTimeIndex]`, so "type" would be `Numeric, DatetimeTimeIndex`

primitive `GreaterThan` has three sets of possible inputs: `[Numeric, Numeric]`, `[Datetime, Datetime]`, and `[Ordinal, Ordinal]`.  "type" would be `Numeric, Datetime, Ordinal`

@SydneyAyx is this the kind ofbehavior you were thinking?
