### ISSUE TITLE
add additional packages to conda-forge

### ISSUE THREAD

**Issue by raybellwaves** [alteryx/featuretools#1188]
Following the install instructions https://featuretools.alteryx.com/en/stable/install.html

there are lots of additional packages which can be installed via pip.

I tend to use conda-forge as my default package installer.

Would it be possible to add some of the other packages to conda-forge? e.g. `autonormalize`.

I find greyskull very useful for doing this https://www.marcelotrevisani.com/grayskull

you could then add extra info for install other packages e.g. `conda install -c conda-forge featuretools tsfresh autonormalize`

**Comment by gsheni** [comment]
@raybellwaves We are in the process of adding tsfresh-primitives to conda-forge:
https://github.com/conda-forge/staged-recipes/pull/16677

**Comment by gsheni** [comment]
Closing in favor of https://github.com/alteryx/autonormalize/issues/43
