### ISSUE TITLE
 [FEA] Benchmark/Workflow for using FeatureTools Deep Feature Synthesis with Pure Pandas /Koalas/Dask 

### ISSUE THREAD

**Issue by VibhuJawa** [alteryx/featuretools#1213]
### Benchmark/Workflow for using FeatureTools Deep Feature Synthesis with Pure Pandas /Koalas/Dask 

I was wondering if there is a workflow benchmark for using FeatureTools for Deep Feature Synthesis with Koalas/Dask/Pandas to get an understanding of expected performance and current computation bottlenecks. A benchmark that does not use custom primitives would be ideal, as that will work with the current Koalas implementation (related [issue](https://github.com/FeatureLabs/featuretools/issues/1142)). 

For more context, I’m exploring the compatibility of FeatureTools with a cuDF/Dask enabled backend, which has been discussed a bit [here](https://github.com/FeatureLabs/featuretools/issues/906).

With this kind of workflow benchmark, I am trying to understand the computational bottlenecks to better scope the examples that might benefit most from GPU acceleration.

**Comment by thehomebrewnerd** [comment]
@VibhuJawa I have done some comparisons between pandas/Dask/Koalas performance, using the same dataset to understand how the three approaches compare in terms of the time required to generate a feature matrix. I will post those results here as soon as I can.

**Comment by thehomebrewnerd** [comment]
@VibhuJawa Here are some comparisons I have done for two different datasets. The tables below contain the time, in seconds, for running each step of the process. I'm sure there could be a lot to discuss here, and feel free to respond below with any questions you might have as you review this.

All of these were run locally on my laptop. To better understand the steps in these, you can refer to these two demo notebooks, which have the same basic flow:

[Predict Next Purchase Demo Notebook](https://github.com/Featuretools/predict-next-purchase/blob/main/Tutorial.ipynb)
[Predict Loan Repayment Demo Notebook](https://github.com/Featuretools/Automated-Manual-Comparison/blob/main/Loan%20Repayment/notebooks/Feature%20Matrix%20with%20Dask%20EntitySet.ipynb)

## Loan Repayment Comparison
![image](https://user-images.githubusercontent.com/4307001/98301431-578c0080-1f80-11eb-92cb-508e64047a5e.png)

## Predict Next Purchase Comparison
![image](https://user-images.githubusercontent.com/4307001/98301469-683c7680-1f80-11eb-892c-059fb261ca43.png)

**Comment by VibhuJawa** [comment]
Thanks for sharing this @thehomebrewnerd , this should help me a lot in my work.  I will keep you posted as I take a deeper dive.

**Comment by VibhuJawa** [comment]
@thehomebrewnerd ,  just a FYI, I posted some initial results with `cudf`   on the benchmark with the cutoff time bits you shared here, https://github.com/alteryx/featuretools/issues/906#issuecomment-731293695  .

**Comment by tyler3991** [comment]
Closing for now. Please reach back out if you have additional questions.
