### ISSUE TITLE
how to do deal test-data(new-data)?

### ISSUE THREAD

**Issue by Jie-Yuan** [alteryx/featuretools#1240]
how to do deal test-data(new-data)?

dfs_model.transform(test_data)?

**Comment by tyler3991** [comment]
Thank you @Jie-Yuan. Please visit https://featuretools.alteryx.com/en/stable/resources/frequently_asked_questions.html#How-does-my-train-&-test-data-work-with-Featuretools-and-sklearn's-train_test_split
