### ISSUE TITLE
Replace Entity with DataFrame (using Woodwork Accessor)

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1253]
- Featuretool's Entity class should be replace with Woodwork's DataFrame (using Woodwork typing via Accessor)
- secondary_time_index should go in metadata of the DataFrame - update example code in release notes
- the last_time_index should be a Series in the metadata of the DataTable (will be changed in #1254)
- For completion, this should allow a use create an EntitySet, add data via Woodwork DataFrame, and add relationships to the EntitySet. 
  - handles interesting_values

**Comment by thehomebrewnerd** [comment]
EntitySet creation should accept both a raw pandas dataframe and a Woodwork Dataframe. If a raw dataframe is supplied, Featuretools should initialize Woodwork (resulting in type inference). If Woodwork is already initialized, Featuretools should use the typing information supplied.

Need to determine what should be done if a user passes a Woodwork dataframe along with other parameters, like `index` or `variable_types` (logical_types). Should Featuretools call the appropriate Woodwork method to set those, or ignore and raise a warning?

**Comment by jeff-hernandez** [comment]
We should test for Woodwork DataFrames with improperly set secondary time indexes

**Comment by thehomebrewnerd** [comment]
> We should test for Woodwork DataFrames with improperly set secondary time indexes

@jeff-hernandez Do you have a specific scenario in mind here? Featuretools will still be setting and validating the secondary time index, correct?

**Comment by jeff-hernandez** [comment]
When we remove `Entity`, we'll also remove one of the spots where we check secondary time indexes. Yes, I'm thinking Featuretools will still be doing the validation.
