### ISSUE TITLE
Put last_time_index in DataFrame metadata and move Series to DataFrame

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1254]
- With #1253, the last_time_index is a Series in the metadata
- However, it should now be moved to be a Series on the actual DataFrame
- The column name should be kept in the metadata of the DataFrame

**Comment by thehomebrewnerd** [comment]
When this is done, we should also review the implementation of `EntitySet.__sizeof__` to make sure the last_time_index is included correctly.

**Comment by thehomebrewnerd** [comment]
As part of this issue, we should also make sure that `test_to_parquet_with_lti` in `test_serialization.py` is working correctly. This test is currently commented out because the lti series stored in the WW metadata is not JSON serializable and fails as a result.
