### ISSUE TITLE
Spike: Investigate the future of Variable class with upcoming Integration

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1255]
- With the Woodwork Integration, we will replace Entity with Woodwork DataFrame, and Primitive Input/Outputs with Woodwork Logical Types/Semantic Tags. If we do this, will we still need the Variable class?
  - Are there methods of properties on the Variable class that cannot be covered with upcoming integration (as defined above). 
- This spike may result in the creation of additional issues.

**Comment by jeff-hernandez** [comment]
We're planning to replace the Variable class with the ColumnSchema. There are issues opened already that cover each aspect of this integration.
