### ISSUE TITLE
Write guide to showing how to transition to the new Featuretools release using Woodwork

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1257]
There are several breaking API changes an other behavior changes associated with the update to use Woodwork dataframes instead of the old `Entity` class. We should write a guide that explains the significant differences, helping users transition to the new release.

### Breaking API Changes
- `Entity.add_interesting_values` has been removed. To add interesting values for a single
  entity, call `EntitySet.add_interesting_values` and pass the id of the entity for
  which to add interesting values in the `entity_id` parameter.
- `Entity.set_secondary_time_index` has been removed and replaced by `EntitySet.set_secondary_time_index`
  with an added `entity` parameter to specify the entity on which to set the secondary time index.
- `Relationship` initialization has been updated to accept four id values for the parent dataframe,
  parent column, child dataframe and child column instead of accepting two `Variable` objects.
- `EntitySet.add_relationship` has been updated to accept dataframe and column id values or a
  `Relationship` object. Adding a relationship from a `Relationship` object now requires passing
  the relationship as a keyword argument.
- `Feature` initialization has been updated - different params are now required
- The `Variable` class has been removed. Primitives must now be defined using Woodwork logical types and semantic tags. And users must now use Woodwork LogicalTypes when manually specifying column types instead of Variables.

### Other Significant Changes to Discuss/Mention
- Column ordering could be different - the index column is no longer guaranteed to be the the first column in the dataframe
- Single `nan` values in LatLong columns will no longer be replaced with `(nan, nan)` tuples
- If a user defines custom primitives, show users how to map their old Variable Inputs to the new Woodwork Logical Types will be helpful.
- The features generated after this update might be slightly different than those previously, primarily a result of a slightly different relationship structure and how foreign key columns are handled when generating features

Once this guide is created, the link to this document inside of the `Woodwork Typing in Featuretools` guide needs to be updated.

**Comment by gsheni** [comment]
- We should make sure to use Jupyter notebooks for the docs, rather than rst files

**Comment by thehomebrewnerd** [comment]
@gsheni Given there are several other breaking changes and other behavior changes that will happen with the integration, do you think we should update this to be a guide that explains more than just the Variable -> LogicalType change, but rather a bigger guide on how to transition between the old approach to the new?

**Comment by gsheni** [comment]
@thehomebrewnerd yes, we can a whole page or section on the new transition for the Entity to DataFrame, adding to EntitySets, defining primitives, accessing typing information for Features. 

Something like this
- https://pycqa.github.io/isort/docs/major_releases/introducing_isort_5.html

**Comment by thehomebrewnerd** [comment]
Ok, sounds good. I will update this issue to capture the significant topics that need to be covered in this transition guide, and we can update as we encounter new things.

**Comment by gsheni** [comment]
One thing to have in the transition guide is an Old vs New. So have a code example of creating an EntitySet the **old** way (doesn't have to run), and then show how the **new** EntitySet creation is done. 

thoughts? @rwedge @thehomebrewnerd @tamargrey @jeff-hernandez @frances-h

**Comment by thehomebrewnerd** [comment]
Closed by #1589
