### ISSUE TITLE
Replace list_variable_types with list_logical_types

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1258]
- To keep breaking changes to a minimum, the `list_variable_types` should return the DataFrame from `list_logical_types` in Woodwork.
- We should also add a `list_logical_types` (which should just return the same thing as Woodwork's `list_logical_types`
- Let's make sure to note this in the Breaking Changes.

**Comment by gsheni** [comment]
Created an additional function fo the semantic tags:
- https://github.com/alteryx/featuretools/issues/1471

**Comment by rwedge** [comment]
Should this be a featuretools function or a woodwork function?

**Comment by gsheni** [comment]
@rwedge Users should be able to do `from featuretools import list_logical_types`, which is just a reference to the Woodwork function. This functionality already exists in Woodwork.

**Comment by jeff-hernandez** [comment]
Closed by #1477
