### ISSUE TITLE
Update DFS's primitive matching to look at Logical Types and Semantic Tags

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1259]
- With the Woodwork upgrade, we will need to update DFS to look at the primitive's input Logical Types and Semantic Tags, and match them up with the information in the Woodwork DataTable
- This relates to the logic for generating the list of features
- This will use the ColumnSchema present on the primitive inputs/return_types
  - The primitive matching logic should take into account when a primitive return_type is None, and allow DFS stacking to still work
- Completion: Call DFS with features_only=True, and it returns a list of Features (using Woodwork typing to determine the list of features).

**Comment by thehomebrewnerd** [comment]
Closed by #1523
