### ISSUE TITLE
Update Entityset schema version with new DataFrame Accessor

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1261]
- With the Woodwork integration, Entity will be replaced with a DataFrame (with Woodwork Accessor)
- This will change the EntitySet save to disk structure, and so it will need to be updated.

**Comment by gsheni** [comment]
The schema version will be upgraded in #1452 and can be closed once that is merged in.

**Comment by thehomebrewnerd** [comment]
Closed by #1452
