### ISSUE TITLE
Update code to replace references to entity/entities with Woodwork DataFrame

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1270]
- Once the Entity object has been removed and replaced by a Woodwork DataFrame, variable names and parameters throughout the code should be updated to replace references to `entity` with new `dataframe` terminology. We should also search for locations where `variable` should be replaced by `column` or `var` by `col`.

- This issue will also involved **replacing entities to DataFrames**

**Comment by gsheni** [comment]
- We should make sure to use Jupyter notebooks for the docs, rather than rst files

**Comment by thehomebrewnerd** [comment]
Closed by #1612
