### ISSUE TITLE
Infer Variable Types Always Returns Numeric For Input Numeric Fields, Regardless of Number of Unique Values.

### ISSUE THREAD

**Issue by SydneyAyx** [alteryx/featuretools#1271]
https://github.com/alteryx/featuretools/blob/753615c89360910768811680a7a71e08ab83ad79/featuretools/utils/entity_utils.py#L85

This bit of logic creates a sample based on the min of 10,000 and the number of unique values in a column. For example, in the titanic dataset the Pclass column has three unique values. Therefore the sample will have three rows in it. 

Then it gets the unique values in the sample set, which can be any combination of [1, 2, 3]. For example, when I ran this the sample had [2, 3, 3] in it. 

Then it calculates the percent_unique by taking the sample.size (three in this case) and dividing by the number of unique values in the sample set, which can be 1, 2 or 3

**percent_unique will never be less than .05 since the number of elements in the sample set is always greater than the number of unique values in it. The conditional if percent_unique < .05 will always be greater than or equal to 1.0 so the type will always be Numeric.**

This was identified by Roland in the code, and Alan has identified this behavior in the Feature Types tool as well.

**Comment by rwedge** [comment]
Looks like we should update the logic to be
```
percent_unique = len(unique) / sample.size
```
