### ISSUE TITLE
how do you rename agg/trans features?

### ISSUE THREAD

**Issue by pchalasani** [alteryx/featuretools#1285]
these have long names like `TIME_SINCE_LAST(events.event_date, unit=days)`

Would be very useful to have some support to easily rename these, rather than having to do it manually.
I couldn't find any issue or SO question related to this, so I'm surprised others haven't wanted this.

**Comment by kmax12** [comment]
thanks for the suggestion. can you expanded on what you mean by not doing it "manually"? what API or functionality are you imagining we add? 

also, have you tried the `FeatureBase.rename()` method on the feature objects? that will allow you to specify a different name for the feature, but you have to do it manually

**Comment by pchalasani** [comment]
Thank you for getting back to me on this. I had in mind a simple way to specify the name of the generated aggregate feature when using `ft.dfs(..., agg_primities = [ft.primitives.TimeSinceLast(unit="days")` -- not exactly sure what syntax I'd want, but I'd want to be able to specify the feature name somewhere "close" to here. I think one of the difficulties is that many features are automatically generated, so it may be hard to specify their names via an API?  I was not aware of `FeatureBase`, will look into it.

**Comment by kmax12** [comment]
i think im following along. can you give an example of what you want it renamed to? that might give us some API ideas

**Comment by tyler3991** [comment]
Closing. Let us know if the proposed solution isn't sufficient and we are happy to discuss!
