### ISSUE TITLE
relationships is not truly optional in ft.calculate_feature_matrix()

### ISSUE THREAD

**Issue by echatzikyriakidis** [alteryx/featuretools#1287]
When I pass just a single entity in ft.calculate_feature_matrix() then I need to pass relationships=().

However, in ft.dfs() I don't have to pass relationships=().

It could be better to continue working with relationships=None to such cases.

Example:

```
new_data_set = ft.calculate_feature_matrix(feature_defs, entities={ "passengers" : (new_raw_data_set, id_column, None, variable_types) }, relationships=())
```

Could be better as:

```
new_data_set = ft.calculate_feature_matrix(feature_defs, entities={ "passengers" : (new_raw_data_set, id_column, None, variable_types) })
```

**Comment by rwedge** [comment]
Thanks for the suggestion, @echatzikyriakidis , that looks like a change we could make!

**Comment by echatzikyriakidis** [comment]
Thank you!

@rwedge Is it possible to ping me when there is a release for this?

Stay safe!

**Comment by rwedge** [comment]
@echatzikyriakidis this is in the latest release!

**Comment by echatzikyriakidis** [comment]
Thank you!
