### ISSUE TITLE
[Question]: How do I understand a relationship?

### ISSUE THREAD

**Issue by dclong** [alteryx/featuretools#1288]
Does a relationship cause an inner join between the 2 entities when generating features? Or does it cause an outer join?

**Comment by mdalvi** [comment]
adding relationships != merging in pandas

Think of it as a groupby() instead, such that if I am adding below relationship to child entity (which is transactions) from my parent entity (which is customers), then I would do all sorts of groupby('customer') on the child.

es = es.add_relationship(ft.Relationship(es['customers']['customer_id'], es["transactions"]['customer_id']))

**Comment by dclong** [comment]
But how is customers and transactions joined? Inner join or outer join?

**Comment by thehomebrewnerd** [comment]
@dclong As @mdalvi suggested, I wouldn't think about this in terms of joins. Behind the scenes, Featuretools is **not** joining or merging the entity data. The id values present in the target entity will determine which id values are carried through to the final feature matrix. Featuretools is traversing the relationships and filtering/grouping the data in related entities based on the id values (and cutoff times, if specified) to calculate aggregation features.

Let's take a `customer -> transactions` relationship as an example, and assume you are targeting the customer entity when generating features. In this case if you have customer_id values that are present in the customer entity, but not in the transactions entity, you will get a row in the feature matrix for those customer ids with default or `NaN` values depending on the feature. Conversely, if you have customer_id values that are in the transactions entity, but not in the customers entity, you will **not** get a row in the feature matrix for these id values.

The id values in the target entity are the key to determining what gets used when generating features.

**Comment by tyler3991** [comment]
Let us know if you have additional questions. Closing.
