### ISSUE TITLE
 Fix v0.9.1 performance bottleneck

### ISSUE THREAD

**Issue by pp7788** [alteryx/featuretools#1326]
### Fix v0.9.1 performance bottleneck
When calculating feature matrix, FeatureTools v0.9.1 would diligently run manual garbage collection, this adds significant latency as seen in the diagram below.

#### Why not upgrade since later versions have removed GC?
Although by upgrading could we avoid this performance issue since later versions have removed manual GC, it is not always feasible, for example:

* Project A depends on library S and Featuretools, S requires pandas to be <= 0.23.4, where Featuretools v0.9.1 can meet that criteria.
* When try to upgrade Featuretools, in order to avoid the incompatible dependency issue, only v0.10.0 and v0.11.0 can be candidates, because versions >= 0.11.0 require pandas >= 0.24.1.
* However, v0.10.0 and v0.11.0 have a bug that causes features not JSON serializable (this bug is fixed in later version), thus, no candidate version is available.

To deal with situations like this, it would be great if v0.9.1 could remove manual GC.

#### Bug/Feature Request Description

Performance comparison v0.9.1 w/ GC vs w/o GC

![image](https://user-images.githubusercontent.com/20734828/106335851-737f0580-6242-11eb-8551-951a907db47d.png)

#### Expected Output
The blue bar in above diagram, expecting the calculation to be much faster.

#### Output of ``featuretools.show_info()``

Featuretools version: 0.9.1

SYSTEM INFO
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

INSTALLED VERSIONS
numpy: 1.16.2
pandas: 0.23.4
tqdm: 4.56.0
toolz: 0.11.1
PyYAML: 5.3.1
cloudpickle: 1.6.0
future: 0.18.2
dask: 2021.1.1
distributed: 2021.1.1
psutil: 5.8.0
scikit-learn: 0.20.2
pip: 21.0
setuptools: 52.0.0

**Comment by rwedge** [comment]
Hi @pp7788, thanks for reaching out!  Would it be sufficient for your use case to install featuretools from your forked repo instead of PyPI?  Then there wouldn't need to be a full release.  It would work something like this:

```
pip install git+https://github.com/pp7788/featuretools.git@v0.9.1_fix_performance_bottleneck#egg=featuretools
```

**Comment by pp7788** [comment]
Hi @rwedge, thank you for the review and advice. 😃 Decided to upgrade featuretools to the latest version anyways, so now actively wrestling with a heavy package that holds back the featuretools upgradation. Again, thank you for your time!
