### ISSUE TITLE
Difficult to change docs version with current layout

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1334]
### Difficult to change docs version

In the [featuretools documentation](https://featuretools.alteryx.com/en/stable/), changing the documentation version is difficult as the "chat with Max" button is displayed on top of the dropdown to change the version. One of these should be relocated to prevent this overlap:

![image](https://user-images.githubusercontent.com/4307001/107228952-de6ad200-69e2-11eb-8971-27b3fc30f67e.png)

**Comment by tyler3991** [comment]
@kmax12 do you want to keep the chat bubble?

**Comment by kmax12** [comment]
i think it makes sense to remove

**Comment by kmax12** [comment]
i've remove the chat from all our pages
