### ISSUE TITLE
DFSTransformer documentation is not correct

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1335]
### DFSTransformer documentation is not correct

A new version of `featuretools.wrappers.DFSTransformer` was released last week, but the Featuretools documentation was not updated, and still shows the docstring from the previous version. Documentation needs to be updated to match the new docstring info.

https://featuretools.alteryx.com/en/stable/generated/featuretools.wrappers.DFSTransformer.html#featuretools.wrappers.DFSTransformer

**Comment by tyler3991** [comment]
Thanks @thehomebrewnerd, I moved this to the "sprint" swimlane

**Comment by tamargrey** [comment]
@gsheni We'll need to update the DFSTransformer to work with the Woodwork integration since its `dfs` call uses entities, and the use of the DFSTransformer in featuretools' documentation will cause the build to fail.

https://github.com/alteryx/featuretools-sklearn-transformer/blob/673095e606e5c6b7f40f346690237e2ea681be63/featuretools_sklearn_transformer/transformer.py#L152

**Comment by gsheni** [comment]
@tamargrey moved this into our current sprint.

**Comment by thehomebrewnerd** [comment]
How should we go about updating these? I think we have a bit of a circular reference problem. We can't build the Featuretools documentation until DFSTransformer is updated, but we can't update DFSTransformer until the new version of Featuretools is released?

Should we remove the DFSTransfomer references from Featuretools for the initial WW integration release, and then add it back in once we have a released version of Featuretools that we can use to update DFSTransformer?

**Comment by rwedge** [comment]
We can make a branch of DFSTransformer that works with the new FT release and have the docs install that

We can release DFSTransformer ahead of FT but make it depend on the unreleased version of FT so it won't be installable

Then release FT shortly after with docs working fine

**Comment by thehomebrewnerd** [comment]
I created two new issues in the featuretools-sklearn-transformer repo:
- [Update to work with Featuretools 1.0.0](https://github.com/alteryx/featuretools-sklearn-transformer/issues/17)
- [Release updated version](https://github.com/alteryx/featuretools-sklearn-transformer/issues/18)

The first should allow us to get the documentation working in the Featuretools repo, and the second covers the actual release of the updated version when we are also ready to release Featuretools 1.0.0.

**Comment by thehomebrewnerd** [comment]
The `main` branch of featuretools-sklearn-transformer has been updated so the code there works with the Featuretools code in the `woodwork-integration` branch. We should now be able to update Featuretools to use the DFSTransformer code from that repo's `main` branch to fix the docs build issues and complete install tests.

**Comment by thehomebrewnerd** [comment]
Closed by #1605
