### ISSUE TITLE
Primitives for Variable Sub-Type?

### ISSUE THREAD

**Issue by HariWu1995** [alteryx/featuretools#1349]
### Request to Support Primitives with Variable Sub-type
Problem: Assume I have 5 numeric variables - Age, Price, PriceSaleOff, Height, Weight,  I want to apply `subtract_numeric` on Price and PriceSaleOff, `multiply_numeric` on Weight and Height, etc but it is impossible if I define all these variables as Numeric, I must define new variable types (Age and Price) and duplicate `subtract_numeric` into `subtract_price`

So, any solution I can apply here? Because any dataset in ML can contain several numeric variables and not all of them should be transformed along with another.

**Comment by rwedge** [comment]
Hi @HariWu1995 , if you would like to apply certain primitives to specific columns, check out our guide in the docs on [specifying primitives options](https://featuretools.alteryx.com/en/stable/guides/specifying_primitive_options.html).  Particularly of note would be the section on [specifying columns for particular primitives](https://featuretools.alteryx.com/en/stable/guides/specifying_primitive_options.html).  

I'll close this issue for now, but feel free to re-open if you that isn't a solution for you!
