### ISSUE TITLE
Move `update_data` from Entity to EntitySet

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1367]
Featuretools should provide an interface for users to update the data that makes up an "entity" in an EntitySet. This is currently done via a method on the `ft.Entity` object, but Woodwork dataframes do not have a corresponding method. To resolve this problem, we can move the `update_data` method from `Entity` to `EntitySet`.

**Comment by jeff-hernandez** [comment]
Closed by #1398
