### ISSUE TITLE
Update generate_description for handling column descriptions that are not set by user

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1374]
### Update generate_description for handling column descriptions that are not set

The current `Variable.description` code contains some logic to make the description human-readable string if not otherwise specified. This code will not exist on Woodwork column descriptions, and column descriptions that are not set by the user will return a value of `None`.

In order to have descriptions remain consistent in Featuretools after Woodwork integration, this code will need to be moved to other places where it is necessary. One place that will like need to be updated is `generate_description` in `feature_descriptions.py`, but there may be other locations as well.

Current `Variable.description` code for reference:
```python
    @property
    def description(self):
        return self._description if self._description is not None else 'the "{}"'.format(self.name)
```

**Comment by rwedge** [comment]
Fixed but by #1403
