### ISSUE TITLE
Replace variable_type in FeatureBase class

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1381]
- With the upcoming integration, variable_type will no longer exist on FeatureBase. The primitive will be defined with a return type that includes Logical Type and Semantic Tag(s). 
- https://github.com/alteryx/featuretools/blob/1f437226cc0610de3af208baf9d788af376b7bb6/featuretools/feature_base/feature_base.py#L179
- This issues needs to update/modify the logic in `variable_type` property to account for this change. The name of the property should be changed as well (`woodwork_type`, `typing_info`, etc)

**Comment by thehomebrewnerd** [comment]
Closed by #1501
