### ISSUE TITLE
Release featuretools 0.23.3 on conda

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1390]
Currently blocked waiting for release of smart_open 5.0.0 on conda-forge

**Comment by gsheni** [comment]
Issue for smart open release here:
https://github.com/conda-forge/smart_open-feedstock/pull/37

**Comment by gsheni** [comment]
@rwedge your MR, smart v5, has been merged.

**Comment by rwedge** [comment]
the featuretools conda-forge PR has been merged, release will be on conda shortly
