### ISSUE TITLE
Calculate Feature Matrix return a Woodwork typed DataFrame

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1393]
- Our DFS/calculate_feature_matrix call can return a Woodwork typed DataFrame.
- This Woodwork typed DataFrame would not need to be validated 
  - (`validation=False, already_sorted=True` during `df.ww.init`).
- The order of the DataFrame returned should be same as the cutoff_time dataframe (if provided) (this is the current behavior).
- We should use the ColumnSchema on primitives to init the **feature_matrix**.

**Comment by gsheni** [comment]
@rwedge Moved #1393 into our next sprint.

**Comment by thehomebrewnerd** [comment]
Confirm that `tests/selection/test_selection.py::test_remove_highly_correlated_features` works after this update
