### ISSUE TITLE
Systematically assign sort order for agg_primitives=['first', 'last']

### ISSUE THREAD

**Issue by S-UP** [alteryx/featuretools#1399]
### Systematically assign sort order for agg_primitives=['first', 'last']

I have transactional data with multiple items ordered within a single transaction per customer. The items purchased all have the same time stamps per transaction ID. 

I want to define systematically how Featuretools generates features for 'first' and 'last' aggregations per transaction ID and customer.

One logic could be to set within each transaction the highest priced item as the first item. But here a problem arises for the 'last' cases where then suddenly the lowest priced item would be selected whereas I would like to select for the last transaction the highest priced item. From how I understand it, selecting as first/last the item with the highest value could be an option. But I would not know how to achieve this.

Questions:
+ How can I systematically define the sort order? Importantly, does FT respect the sort order as provided in the input data?
+ How to go about getting the highest or lowest value item per transaction (not their value but the item name)

**Comment by rwedge** [comment]
> How can I systematically define the sort order? Importantly, does FT respect the sort order as provided in the input data?

`EntitySet.entity_from_dataframe` has the `already_sorted` parameter which tells Featuretools if the input data has already been sorted.  If set to `True`, Featuretools will respect the provided sort order.  If `already_sorted=False` and the data has a time index, Featuretools will sort the data first on time index and then by the index column

> How to go about getting the highest or lowest value item per transaction (not their value but the item name)

One way to approach this would be to put the individual items from a transaction in another table (we could call it transaction_items) that would have the transactions table as its parent table.  So the relationship between tables would be "a customer can have many transactions, a transaction can have many items".

With this relationship structure, it's easy to get the highest price item of the first or last transaction of a customer by stacking features.  First we take the base feature, highest priced item of a transaction,  by appling the max primitive: `MAX(transaction_items.price)`.  Then we could stack the First or Last primitive on that feature to make it a customer-level feature - `FIRST(transactions.MAX(transaction_items.price))` or  `LAST(transactions.MAX(transaction_items.price))`.

I hope I've answered your questions.  I'm going to close the issue but if you would like to discuss the topic more feel free to reopen the issue!
