### ISSUE TITLE
Primitive: missing value indicator

### ISSUE THREAD

**Issue by dsherry** [alteryx/featuretools#1401]
#### Feature Request Description

Indicate whether each row in a particular feature was or was not a missing value (`nan`).

#### Expected Output

For a particular column, output True if the value on a given row was `nan`, and False otherwise.

**Comment by rwedge** [comment]
I think this IsNull primitive covers this use case

https://primitives.featurelabs.com/#IsNull

**Comment by dsherry** [comment]
Omg thank you @rwedge !
