### ISSUE TITLE
Update EntitySet.concat to use Woodwork

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1419]
Will allow combining two Entity Sets to create a new EntitySet with both sets of DataFrames. Uncomments the code in `entityset.py`, updates it to use Woodwork dataframes, and updates the corresponding `test_concat_entitysets` test in `test_es.py`.

Might make use of Woodwork concat since at one point in the current implementation we do `combined_df = pd.concat([self_df, other_df])`, so we'll need a good way of concating the TableSchema of those two DataFrames.

This implementation will use normal pandas concat.

**Comment by thehomebrewnerd** [comment]
The test for entityset concat uses deep copies of entitysets and relies on `query_by_values`. As a result, issues #1362 and #1420 need to be closed before this can be completed.
