### ISSUE TITLE
Include deep check of Woodwork dataframes in EntitySet equality check

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1424]
When `EntitySet.__eq__` was updated to use Woodwork DataFrames, there was no ability to pass a `deep` parameter to Woodwork's equality checks, so it was not included in the EntitySet equality check. With the current implementation, entityset equality checks will always do a deep check, looking at data equality (for Pandas dataframes only). We should allow a shallow check that does not check for data equality.

Now that Woodwork allows the `deep` parameter, we should add it in the equality check as `if not df.ww.__eq__(other[df_id].ww, deep=deep)`.

We should also update the corresponding entityset equality test to include some deep and shallow checks.

**Comment by thehomebrewnerd** [comment]
The current `deep` equality check in Woodwork will not check that the underlying data is equal for Dask/Koalas dataframes. In the old Featuretools entity equality check a custom `_dataframes_equal` function was implemented for checking the equality of dataframes.

As part of this issue, we should also investigate whether we should also include use of the custom `_dataframes_equal` function for Dask/Koalas dataframes as well as investigate whether the current deep equality check implemented in Woodwork for pandas is significantly slower than the `_dataframes_equal` function to understand if the Woodwork implementation has introduced a significant performance degradation for Featuretools.
