### ISSUE TITLE
Add list_semantic_tags function to get all semantic tags 

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1471]
- Users should be able to import a `list_semantic_tags` from featuretools. 
- This will allow users to see all the standard/supported/suggested semantic tags in Featuretools
- This function will just return the Woodwork function:
  - https://woodwork.alteryx.com/en/latest/generated/woodwork.type_sys.utils.list_semantic_tags.html?highlight=list_semantic_tags

**Comment by jeff-hernandez** [comment]
Closed by #1486
