### ISSUE TITLE
Update WW min version to 0.4.1

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1474]
Woodwork version 0.4.1 contains bug fixes that are needed as part of the integration into Featuretools. Once Woodwork version 0.4.1 is released we should update `requirements.txt` with this Woodwork version to allow tests that are currently failing due to the bugs to pass.

#### Tests failing due to WW bugs:
- test_serialization.py::test_test_to_csv
- test_serialization.py::test_to_csv_manual_interesting_values

**Comment by gsheni** [comment]
Closed in https://github.com/alteryx/featuretools/pull/1478
