### ISSUE TITLE
Handle `make_index` logic directly in featuretools instead of passing to Woodwork

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1491]
Woodwork will be removing the `make_index` logic in [this issue](https://github.com/alteryx/woodwork/issues/984), so Featuretools' `EntitySet.add_dataframe` should handle the logic for adding a column to the dataframe before initializing Woodwork on it.

That the DataFrame had an index created for it should be stored in the Woodwork metadata as `'make_index': True` to be used later on. The following changes should be made:
- handle index column creation directly in `EntitySet.add_dataframe`, adding `make_index` to the DataFrame's metadata.
- Remove any references to the Woodwork `make_index` attribute
- add test to confirm that the make index value is maintained across a deepcopy
- add test to confirm that the make index value is included in equality check (it will only be in the deep equality check, because shallow doesn't check the Woodwork metadata)
- Handle `update_dataframe` in a case where an index was made for the original dataframe, in cases where the new dataframe both does and does not have the made index column. (currently not handled at all)

**Comment by thehomebrewnerd** [comment]
Closed by #1507
