### ISSUE TITLE
Remove Entity class definition

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1497]
- With the Woodwork integration, the Entity class will be replaced with a Woodwork typed Dataframe
- The class definition and code should be completely removed, as it no longer be used

**Comment by tamargrey** [comment]
Other things that can likely be removed as well:
- `_check_time_type` - this is no longer necessary, as this check is now a part of `_get_time_type` as it uses `series.ww.is_numeric` and `series.ww.is_datetime`
- DEFAULT_DTYPE_VALUES

**Comment by thehomebrewnerd** [comment]
`entity.py` was removed in #1501, but there are still a few tests in `test_entity.py` that need to be reviewed to make sure they care covered elsewhere before they are deleted.

**Comment by jeff-hernandez** [comment]
Closed by #1521
