### ISSUE TITLE
Standardize how woodwork is imported in the codebase

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1510]
Woodwork is imported in a handful of ways

`import woodwork as ww`
`from woodwork import logical_types as ltypes`
`from woodwork.logical_types import Numeric`
`from woodwork.column_schema import ColumnSchema`

We should look at the various scenarios where we import woodwork and decide on standard ways to import based on the scenario.

**Comment by jeff-hernandez** [comment]
Closed by #1526
