### ISSUE TITLE
Review and confirm DFS behavior after updating CFM

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1530]
### Review and confirm DFS behavior after updating CFM

PR #1253 has made updates to deep feature synthesis such that the features returned from DFS can be different than those currently returned by the released version of Featuretools. The main reason for this is because of the way foreign key columns are treated. The updated will not generate any features from numeric foreign key columns, while the current release treats all foreign key columns as categorical variables and will generate features.

Once CFM has been updated, we should revisit this behavior to make sure that we are still satisfied with the way foreign key columns are generated and that there are no other DFS issues that need to be addressed. We should benchmark the performance of DFS against the current release to make sure there are no significant performance regressions with the new code.

We want to look at the **features we are generating with the integration** and make sure they are **similar to the old features** we would generate.

**Comment by rwedge** [comment]
Since the `return_types` of `dfs` by default do not include `NaturalLanguage`, `flight_id` wasn't returned

**Comment by tamargrey** [comment]
> Since the `return_types` of `dfs` by default do not include `NaturalLanguage`, `flight_id` wasn't returned

ahh, makes sense!

**Comment by thehomebrewnerd** [comment]
Some initial findings from investigating the features returned from the performance test datasets:
- The current branch of `woodwork-integration` is generating features from the last time index columns that are now being added to the dataframes. This should not be the case and Issue #1693 was created to resolve this
- Woodwork now assigns a logical type of `Unknown` to columns that contain all null values. Previously these columns could have been inferred as a numeric column, and numeric features could be generated from the column. With the integration, features are no longer generated from these columns. The new behavior seems appropriate.
- In many tests, we are not generating features from boolean columns that were previously generated. The root of this issue is likely that the first input to the primitives that take boolean columns is `BooleanNullable` but boolean columns in the EntitySet are typically inferred with a `Boolean` logical type, so DFS is not generating features for these columns now. This behavior seems a bit problematic. It can be resolved by manually setting the logical type for the columns in the EntitySet to `BooleanNullable`, but it would be nice if users did not have to do this for features to be generated from these columns.

**Comment by thehomebrewnerd** [comment]
I also did some spot checking of the features that had different values between the current release and the Woodwork update. The main difference I found was in boolean features. Previously these columns would not contain any null values, so we would get features like this:
```
feature_matrix['cancel_date < NUM_UNIQUE(log.zipcode)']
id
2    False
0    False
1    False
Name: cancel_date < NUM_UNIQUE(log.zipcode), dtype: bool
```

Now, with the `BooleanNullable` return type, we get this instead:
```
feature_matrix['cancel_date < NUM_UNIQUE(log.zipcode)']
id
2     <NA>
0    False
1    False
Name: cancel_date < NUM_UNIQUE(log.zipcode), dtype: boolean
```

The new behavior here seems better as we aren't treating missing values as `False`.

There was one feature that was different in the zillow tests, but this is a result of column type differences and could be resolved by ensuring the column types are equivalent.

**Comment by thehomebrewnerd** [comment]
The significant differences between old and new features have been documented above. Based on the integration of Woodwork, these differences seem expected. As a result, I do not believe further work is required at this time, but we can reopen this issue or create a new issue in the future if the differences in features returned is found to be problematic.
