### ISSUE TITLE
Test dask/koalas primitive compatibility for email / url primitives

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1549]
The primitives `URLToProtocol`, `URLToDomain`, `URLToTLD`, `EmailAddressToDomain`, and `IsFreeEmailDomain` should be tested for compatibility with Dask/Koalas and their `compatibility` lists updated accordingly

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
