### ISSUE TITLE
Use feature origin attribute from ColumnSchema when generating feature matrix

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1559]
- Woodwork v0.5.0 added a feature origin attribute
  - https://github.com/alteryx/woodwork/pull/1056
- We should use when after we generate the feature matrix to specify which features were **engineered** and which features were **source**
- You can use the feature definitions to specify the **origin**. 

- We should also update the documentation (Woodwork Typing in Featuretools guide) to specify where this information, what it means and how users can access it.

**Comment by tamargrey** [comment]
Should seed features get their own origin value?

**Comment by rwedge** [comment]
I think they can be seen as user-specified engineered features, I don't think they need a separate value
