### ISSUE TITLE
Investigate suppressing cells in jupyter notebooks

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1560]
Featuretools currently uses many rst files for its docs, and in those docs, if we want to hide a cell containing imports or config settings that are not important for a reader's understanding of the guide, we use `:suppress:`. An example of this is the max columns setting that we set at the beginning of the `handling_time.rst` file:

```python
.. ipython:: python
    :suppress:

    pd.options.display.max_columns = 200
```

As we convert these rst files to jupyter notebooks, it seems like suppressing these cells may not be as simple as adding the above snippet to a rawNBConvert rst cell.

For example, if I add the following two cells to an rst file, the results compile. However, if I add the first as a suppressed raw rst cell and the second as a normal code cell, the pandas import error (`NameError: name 'pd' is not defined`) is shown. If both cells are in raw rst cells, there is no error and the docs compile. 

```python
.. ipython:: python
    :suppress:

    import pandas as pd

.. ipython:: python

   pd.DataFrame()
```
Interestingly, if the order is switched (we first make a pandas call and then import pandas), there is also no error if we add that snippet to an rst file or if added to a notebook where the first cell is the raw rst and the second with the pandas import is a normal code cell.

Talked with @frances-h a bit about this, and we think there might be some issue with the order that the raw rst cells get executed.

We have a few options here:
1. Investigate how to suppress these cells in jupyter notebooks
2. Stop trying to hide these cells, but make sure that they're present in a way that makes it clear that they're not important for understanding the guide.
3. Don't use jupyter notebooks if we really need to suppress a cell

One other point of interest is in the `using_koalas_entitysets.rst` guide where we have the following block:

```python
.. ipython:: python
    :suppress:

    import pyspark.sql as sql
    spark = sql.SparkSession.builder.master('local[2]').config("spark.driver.extraJavaOptions", "-Dio.netty.tryReflectionSetAccessible=True").config("spark.sql.shuffle.partitions", "2").config("spark.driver.bindAddress", "127.0.0.1").getOrCreate()    
```

In woodwork, we have the same config setting that we eventually had to stop suppressing because of an inconsistent error that was produced: https://github.com/alteryx/woodwork/issues/803 . In that issue, we note that it works here in featuretools' rst file, so it might be an issue with jupyter notebooks. I'm guessing we'll run into the same issue if/when we convert that guide to jupyter notebook.

If we can better understand how these raw rst cells get executed/if we can successfully suppress these cells, that might help us with that issue.

**Comment by frances-h** [comment]
This can be done by adding `"nbsphinx": "hidden"` to the cell's metadata. It'll get executed like a normal jupyter notebook cell, but the contents and output will remain hidden.

https://nbsphinx.readthedocs.io/en/0.2.1/hidden-cells.html
