### ISSUE TITLE
Update Tuning Deep Feature Synthesis Page with Woodwork Dataframe 

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1569]
- The page below should be updated with the new function calls, parameters, and the accessor approach.
- https://featuretools.alteryx.com/en/latest/guides/tuning_dfs.html
- We should also at the same time **use Jupyter notebooks, rather than RST files.**

**Comment by tamargrey** [comment]
An `UnusedPrimitiveWarning` is being raised for the dfs call with the pimitives `"count"` and `"avg_time_between"`. Not sure if the type definitions are different in a way that these primitives don't get used anymore or if there's some other problem, though.

**Comment by tamargrey** [comment]
> An `UnusedPrimitiveWarning` is being raised for the dfs call with the pimitives `"count"` and `"avg_time_between"`. Not sure if the type definitions are different in a way that these primitives don't get used anymore or if there's some other problem, though.

For the record: this was because the setting of `interesting_values` needed to be updated to match the new api.
