### ISSUE TITLE
Update FAQ with Woodwork Dataframe

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1578]
- The page below should be updated with the new function calls, parameters, and the accessor approach.
- https://featuretools.alteryx.com/en/latest/resources/frequently_asked_questions.html
- We should also at the same time **use Jupyter notebooks, rather than RST files.**

**Comment by tamargrey** [comment]
We should add a question under the EntitySets section on `How do I update a column's description or metadata` that explains that you'll need to go through `df.ww.columns[col_name]` to update attributes like description and metadata and that doing `df.ww[col_name]` will give you a new Series object, so if you use that syntax, any changes won't get made on the EntitySet itself.

**Comment by jeff-hernandez** [comment]
Closed by #1649
