### ISSUE TITLE
Fix remaining Woodwork integration tests that have been skipped

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1596]
The following tests need to be fixed as part of the Woodwork integration. The reason these tests are failing are documented along with the test. All of these tests have been skipped with pytest.skip for the time being. Once the issues are resolved, these xfails should be removed

**featuretools/tests/entityset_tests/test_es.py::test_concat_with_lti[dask_es]**
- This test fails for Dask because Woodwork creates an error that shows up on .compute() caused by this line `updated_series = self[dataframe_name].ww.logical_types[col_name].transform(series)` in `EntitySet.update_dataframe`. This error happens when trying to run `transform` for the two `LatLong` columns in the `log` dataframe
- [Woodwork Issue 1099](https://github.com/alteryx/woodwork/issues/1099) has been created for this problem

**featuretools/tests/primitive_tests/test_dask_primitives.py::test_transform**
- This test is failing because of a Dask issue with series.eq returning different values than the pandas equivalent. This is documented in [Dask Issue 7957](https://github.com/dask/dask/issues/7957).

**featuretools/tests/selection/test_selection.py::test_remove_highly_correlated_features**
- This code executed as part of this test attempts to use Woodwork `select` on the feature matrix. However, at this stage Woodwork is not initialized on the returned feature matrix, so this results in an error. Once Featuretools returns a Woodwork initialized feature matrix this test can be fixed.

**featuretools/tests/synthesis/test_koalas_dfs.py::test_single_table_ks_entityset_cutoff_time_df**
- This failure should be revisited after the feature matrix has WW initialized. In the current release the column `IS_WEEKEND(dates` is returned as a float64 column (instead of a boolean) because of two missing values. Without Woodwork initialized on the feature matrix, this column is now being returned as a type `object` for pandas with values of `False, NaN, Nan, 0.0`. Koalas returns a column with `False, None, None, False`. Once this column is set with the proper dtype, these values should match. The values in other columns match but there are some dtype differences.

**Comment by gsheni** [comment]
@thehomebrewnerd moved this into our current sprint.

**Comment by gsheni** [comment]
As this is not required to finish the integration, moving this issue to the follow up to Woodwork integration Epic

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
