### ISSUE TITLE
Update index.rst to use Woodwork

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1598]
The index.rst file makes a `dfs` call with an `entities` dictionary. We should switch that dectionary to be `dataframes` and pass that into dfs.

We should also update the wording in the guide to remove references to `entities`. 

We should **use ipynb rather than rst**.

**Comment by gsheni** [comment]
@tamargrey this page needs also to be updated to be a ipynb notebook, right?

**Comment by tamargrey** [comment]
@gsheni Yeah, using an ipynb notebook makes sense!
