### ISSUE TITLE
Update featuretools-sklearn-transformer version requirement in Featuretools

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1606]
In the `woodwork-integration` branch, `featuretools-sklearn-transformer` is being installed from the `ft-1.0.0-dev` branch of the repo in order to install a versions of the code that works with the Woodwork integration, which in turn, allows the API documentation to build properly. 

Before releasing Featuretools 1.0.0, we should update `dev-requirements` to install `featuretools-sklearn-transformer` from pypi again and remove the install from Github. 

Also, setup.py should be updated to install the proper versions of `featuretools-sklearn-transformer`.

**Comment by gsheni** [comment]
1. Add back     `'sklearn_transformer': ['featuretools-sklearn-transformer >= 1.0.0']` as an `extra_requires` in setup.cfg
3. Add back reference in api_reference.rst
4. Add it back in `install.md`
5. Check if anything else is missing from when it was removed: https://github.com/alteryx/featuretools/pull/1644/files
