### ISSUE TITLE
An index column created in `EntitySet.replace_dataframe` should start from where the original DataFrame left off.

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1631]
Currently, if a user replaces a DataFrame in their EntitySet and the original DataFrame had an index column created for it, the new DataFrame's index column will range from `0` to `len(new_df)` even though the original DataFrame's index column also ranged from `0` to `len(old_df)`.

This means that there will be overlap in the "unique" indices between the two DataFrames. It's not clear whether this may cause problems later on, but it does seem unexpected if you imagine that the old dataset is the training data and the new dataset is the test data. If you're imagining the the new DataFrame is replacing the old because it was bad data, this is less of a problem.

We should consider changing `replace_dataframe`'s create index behavior to start where the original dataframe left off.

We could do this by updating `_create_index` to take in a `start_value` parameter that determines the first value of the index column. This would default to `0` in `add_dataframe`, but be `len(df)` in `replace_dataframe`. This could also be managed by a parameter in `repalce_dataframe` to allow users to choose whether

**Comment by gsheni** [comment]
Not doing as there is not a use-case for it
