### ISSUE TITLE
How to specify aggregate functions for categorical features

### ISSUE THREAD

**Issue by Jie-Yuan** [alteryx/featuretools#1634]
How to specify aggregate functions for categorical features

**Comment by jeff-hernandez** [comment]
Hey @Jie-Yuan! Thanks for the question. You can specify aggregation functions for categorical features by making custom primitives. For example, if you want to create an aggregation function to count the number of unique categories, derive a subclass from `AggregationPrimitive` and define the aggregation function inside `get_function()`. 

```python
from featuretools.primitives import AggregationPrimitive
from featuretools.variable_types import Categorical, Numeric


class NumUnique(AggregationPrimitive):
    name = "num_unique"
    input_types = [Categorical]
    return_type = Numeric

    def get_function(self):
        def num_unique(categorical):
            return categorical.nnunique()

        return num_unique
```

You can learn more about defining [simple custom primitives](https://docs.featuretools.com/en/stable/getting_started/primitives.html#Simple-Custom-Primitives) and [advanced custom primitives](https://docs.featuretools.com/en/stable/guides/advanced_custom_primitives.html#Advanced-Custom-Primitives-Guide) in the linked pages. Let me know if you found this helpful.
