### ISSUE TITLE
Quirk if dataframes have NaN in index and Woodwork integration

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1680]
Featuretools allows creating an entity/dataframe with NaN as one of the index values, but when calculating aggregations for that value it does retrieve the value succesfully.  In this example, user 4 is a user with a null favorite color.  Calculating the feature "last user with a favor color of null" you'd expect the result to be 4 since they're the only user with that "color" chosen, but instead featuretools returns NaN for that feature.

```python
import featuretools as ft
import pandas as pd

df = pd.DataFrame({'user': [0, 1, 2, 3, 4],
                   'join_date': pd.date_range(start="2001-1-1", periods=5),
                   'favorite_number': ["blue", "red", "blue", "green", None]})

es = ft.EntitySet("test")

es.entity_from_dataframe(entity_id="users",
                         dataframe=df,
                         index="user",
                         time_index="join_date")

es.normalize_entity(base_entity_id="users",
                    new_entity_id="colors",
                    index="favorite_color")

feature_matrix, feature_list = ft.dfs(entityset=es, target_entity="users", agg_primitives=["last"])

feature_matrix['colors.LAST(users.user)']
```

**Comment by gsheni** [comment]
Closing in favor of https://github.com/alteryx/woodwork/issues/1191, which will prevent this
