### ISSUE TITLE
Add dataframe with entityset setter

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1685]
- With Featuretools 1.0.0 we add a dataframe to an EntitySet with the following:
```
es = ft.EntitySet('new_es')

es.add_dataframe(dataframe=orders_df,
                 dataframe_name='orders',
                 index='order_id',
                 time_index='order_date')
```
# Improvement
- However, you could also change the EntitySet setter to add it with this approach:
```
es = ft.EntitySet('new_es')
es['orders'] = orders_df
```
- In this case, Featuretools would assume the 1st column in the dataframe is the index (current behavior in Feature < 1.0.0)
- The time index would be None
- already_sorted would be False

**Comment by tamargrey** [comment]
a couple of questions:
- does this allow the dataframe being set to be initialized with woodwork already?
- What happens if there's already a dataframe with that name in the entityset? Same behavior as with `add_dataframe`?

**Comment by gsheni** [comment]
@tamargrey 
1. Yes, it does. If the dataframe is already initialized, we can do some checks in Featuretools (check the df name)
2. We should raise an error in this case.

**Comment by rahulbanerjee26** [comment]
Hi, is this issue up for grabs?

**Comment by gsheni** [comment]
@rahulbanerjee26 yes, this issue has not taken yet. Feel free to put up an MR with the implementation + unit test. You can look at our contributing guide:
- https://github.com/alteryx/featuretools/blob/main/contributing.md

**Comment by dvreed77** [comment]
@gsheni I think as a user I would expect this to be more of a convenience function for `add_dataframe` and so should simply pass key as `dataframe_name` and value as `data_frame`. In other words it shouldn't error out if name is already taken.

**Comment by gsheni** [comment]
Looking at this again, I see what you mean. We can go with that behavior (no error if name is already taken).

**Comment by thehomebrewnerd** [comment]
Just keep in mind that if we allow that behavior (no error) and the new dataframe is different than the existing dataframe, especially in terms of columns present, we could get some funky errors during DFS/CFM if columns involved in relationships or features that have already been generated are no longer present.

Maybe we should confirm that the new columns/column types are the same if the dataframe already exists? Not sure.

**Comment by dvreed77** [comment]
@thehomebrewnerd I would expect all that checking to be done in `add_dataframe` though. I would expect the `__setitem__` call to directly call `add_dataframe`.

**Comment by thehomebrewnerd** [comment]
Hmmm. Maybe I'm not remembering how things work correctly...

**Comment by thehomebrewnerd** [comment]
Yeah, looks like I was not correct in remembering how things worked. Please disregard my earlier comment and carry on.
