### ISSUE TITLE
CFM with instance ids that are entirely after cutoff time raises TypeConversionError for non nullable logical types

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1692]
When calculate feature matrix is called with a cutoff time that is a single datetime and instance ids, the former implementation would include all instance ids as rows in the resulting feature matrix, and if any instance ids were entirely after the cutoff time, that row in the feature matrix would be fully null.

In Woodwork, this causes issues in columns whose logical types are not nullable, for example, an `Integer` column.

If we look at the three transaction ids `[1, 2, 3]` in the transactions dataframe, we can see that `1` and `3` have a `transaction_time` that is after the cutoff time `"2014-1-1 04:00"`.

![image](https://user-images.githubusercontent.com/64278226/133303325-1acc3565-39f6-40e9-a23b-8e5bf73aba54.png)

So if we use those transaction ids as instance ids with the `"2014-1-1 04:00"` cutoff time, the rows in the resulting DataFrame should be filled with nans.

```python
from featuretools.tests.testing_utils import make_ecommerce_entityset

es = ft.demo.load_mock_customer(return_entityset=True, random_seed=0)

fm, features = ft.dfs(entityset=es,
                      target_dataframe_name='transactions',
                      cutoff_time=pd.Timestamp("2014-1-1 04:00"),
                      instance_ids=[1,2,3] #1 and 3 are entirely after the cutoff time
                     )
```
However the following error is thrown when calculate feature matrix is executed in the above code: `TypeConversionError: Error converting datatype for session_id from type float64 to type int64. Please confirm the underlying data is consistent with logical type Integer.`

This is because the logical type of `session_id` is `Integer`, which cannot handle null values. 

We should either update the logical type in this case to `IntegerNullable` or consider dropping the rows altogether (This is what happens when no instance ids are supplied).

**Comment by thehomebrewnerd** [comment]
The idea for [this Woodwork issue](https://github.com/alteryx/woodwork/issues/1119) arose from this issue as well. If Woodwork had the ability to gracefully fall back to nullable types when nulls are present that would also resolve this problem.

**Comment by rwedge** [comment]
This issue can also happen when using a cutoff time dataframe

**Comment by leahmcguire** [comment]
This issue can also happen if you are doing a join between tables and not every row in parent table has a corresponding row in the child table. Is there a suggested workaround for this?

**Comment by gsheni** [comment]
@leahmcguire thanks for raising the concern. We are planning to address this sometime in December.
