### ISSUE TITLE
Change name of date_of_birth to birthday

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1697]
- A better name date of birth column in our mock dataset would be `birthday`.

**Comment by LEO2822** [comment]
hello sir can i get this issue done, i can solve this issue so can you please assign this issue to me. i am new to github and open source so i dont know much , but i have decent knowledge regarding data science and all so can i get this is issue done.

**Comment by LEO2822** [comment]
@gsheni sir so i would like to request you to assign this issue to me . thank you sir.

**Comment by gsheni** [comment]
@LEO2822 thanks. I have assigned you the issue. You can look at the contributing documentation here
- https://github.com/alteryx/featuretools/blob/main/contributing.md

**Comment by LEO2822** [comment]
@gsheni hello sir the work is almost done, but I don't know what to do with the make test and make lint as they are giving me errors. So can you please tell me how can I run the test and linting ?

**Comment by gsheni** [comment]
@LEO2822 What is the error you are getting?

**Comment by LEO2822** [comment]
It says that the make test command doesn't exist in bash and same goes for the make lint as well. @gsheni so how can i run the test ?

**Comment by thehomebrewnerd** [comment]
@LEO2822 This error is telling you that you don't have `make` installed properly in your system.

**Comment by LEO2822** [comment]
So how can you tell me how can i run this commands -

```
Make run
Make lint
```
@thehomebrewnerd

**Comment by thehomebrewnerd** [comment]
@LEO2822 You need to have `make` installed on your computer. I'm not sure what type of computer you are running on, but Google can help you with how to properly install on your system.

**Comment by LEO2822** [comment]
@thehomebrewnerd yeah i tried so many sites and eent through stackoverflow posts but didn't got any feasible solution.

I am using windows 10.. can u share some link or site that can help solve this issue

**Comment by thehomebrewnerd** [comment]
I'm not a Windows user, so I won't be much help here.

Even without make you can run the corresponding commands that are present in `Makefile`: https://github.com/alteryx/featuretools/blob/main/Makefile

`make test` just runs `pytest featuretools/`

`make lint` runs `flake8 featuretools && isort --check-only featuretools` followed by `python docs/notebook_cleaner.py check-execution`

**Comment by LEO2822** [comment]
@thehomebrewnerd, as you said, I ran the file in CLI, and it went smoothly…
[output_makefile.txt](https://github.com/alteryx/featuretools/files/7250384/output_makefile.txt)
here is the file which shows the output of the Makefile after running, please confirm the result and let me know if there are any changes I have to make!

**Comment by gsheni** [comment]
@LEO2822 You can put up the MR, and we can better assist you. We will be able to see the changes, and may be able to tell you what is causing the error.
