### ISSUE TITLE
Fix codecoverage of EntitySet.__eq__ method

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1712]
The integration of Woodwork resulted in three lines in the `EntitySet.__eq__` method that were previously covered by tests, now being uncovered. We should update the equality tests to make sure all conditions are properly covered by tests.

The conditions that are not covered are shown below:
![image.png](https://images.zenhubusercontent.com/5da89a3c8b7bd200019886b7/dbbaa7d5-9c2d-4b29-acbf-a0461afc8a60)

**Comment by HenryRocha** [comment]
Hello! If possible I'd like to take this on as my first contribution.

**Comment by thehomebrewnerd** [comment]
@HenryRocha Yes, feel free to work on this issue. If you have not seen this already, here is some info on contributing:
- https://github.com/alteryx/featuretools/blob/main/contributing.md

The relevant tests can be found in `test_entityset.py`, in particular look at the test called `test_entityset_equality`. I'm a little surprised these lines were showing up as uncovered, so you might want to double check my coverage report from above before you do too much work, as it's possible the coverage report was in error.
