### ISSUE TITLE
Add test to verify all primitives can be initialized without passing parameter values 

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1717]
## Add test verify all primitives can be initialized without passing parameter values

We should add a test to make sure that all standard primitives can be initialized without passing any parameter values. If initialization is not possible, running  `get_valid_primitives` will result in an error. Adding a test will make sure any new standard primitives are created with default values specified for all parameters.

**Comment by rwedge** [comment]
I think between testing `get_valid_primitives` and the `test_init_and_name` tests we are covering this scenario, but an explicit test for this scenario couldn't hurt
