### ISSUE TITLE
Update conda install commands to specify channel

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1718]
- All conda install commands should specify the channel to use (`conda install -c conda-forge featuretools`)
  - https://github.com/alteryx/featuretools/search?q=conda+install 
- For example, [our botocore error message](https://github.com/alteryx/featuretools/blob/9814869c7ec50d0313dd590b079c37c0fd24765a/featuretools/utils/s3_utils.py#L59), does not specify the channel

**Comment by kushal-gopal** [comment]
Hello, @gsheni. Just checking if this needed to be worked on?

**Comment by gsheni** [comment]
@kushal-gopal You can pick up this issue. I just assigned it to you
