### ISSUE TITLE
Spike: Refactor Rolling primitives

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1730]
Feature engineering for time series problems often makes use of "delayed" (or lagged) copies of the original data that shifts relevant columns in the original dataset in order to provide each row with information about previous observations. This is useful for time series problems where the data has an inherent, temporal ordering and knowing information about earlier observations can inform predictions about future observations. 

The sort of features that featuretools should be able to create for a value at time `t=0` are:
- previous observation - the observation immediately prior to `t` at `t - 1`
- the observation a specified amount of time prior to `t` - the observation at `t - 7` to get the observation a week ago for data with a daily frequency.
  - or any "meaningful" multiples of the data frequency. So data with a daily frequency is meaningful at [7, 14, 28, 365]. Data with a weekly frequency could be meaningful at [2, 4, 52].
- any number of these observations
  - the last `k` observations - the observations between `range(t - k, t)` or, if we only want to include one observation each week over the last `k` weeks of daily data: `range(t - 7k, t, 7)`

EvalML's `DelayedFeatureTransformer` makes use of this kind of feature engineering via the `series.shift` pandas operation [here](https://github.com/alteryx/evalml/blob/27198716f31a0e1661b0d4733c960be0d94c1acf/evalml/pipelines/components/transformers/preprocessing/delayed_feature_transformer.py#L127
). There, EvalML uses the `start_delay` and `max_delay` attributes to determine the length of the window of time each value will have access to, creating new columns for the feature matrix. 

Featuretools may be able to perform this kind of feature engineering by viewing the columns created as multi-output features created from a transform primitive that sets `number_output_features` to be equal to a `window_length` parameter. The primitive may also need `uses_full_dataframe = True`, as it will access earlier values in the dataframe. This primitive should also take in a `gap` parameter that determines whether the prior observations are taken from immediately before a value or whether there is a gap of time. `gap` and `window_length` have to be functional with EvalML's `start_delay` and `max_delay`.

As the usefulness of shifted data depends on the existence of a time index, the one of the inputs should be a time index column. Additionally, users may need to be aware that, for this primitive to function, the data passed in will have to have a constant interval of time between observations (frequency).

To determine
1. Is there a way for DFS to restrict use of this primitive to columns with a known frequency? Or will correct usage require the creation of seed features? Of is a frequency not actually necessary?
2. Is there a way to get around the use of an integer `window_length` and instead use a [date offset string](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects) like we do for the`training_window` parameter to dfs?
    - using integers for the window length implies that there is a constant interval between observations, but if a date offset string is used, then we can't shift by a certain number of rows unless a frequency is defined and it matches the frequency of the data. If we want to use date offset strings, we need to find a different, likely more complicated way to achieve these delayed features.
3. For input types, is a Datetime column enough? Or does it need to be a time index? Is numeric time index okay?
4. What are the return types? Shifted columns will have null values because of the offset, so any return type needs to be nullable or otherwise have ways of handling these nulls.

**Comment by gsheni** [comment]
Related primitive: https://github.com/alteryx/featuretools/issues/1781
