### ISSUE TITLE
Spike: Investigate additional time series primitives

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1735]
In addition to adding primitives that can calculate delayed features in #1730, Featuretools can better support time series problems by investigating existing or potential new primitives that will allow users to build features that elucidate temporal trends like:

- Special event indicators (holidays and key events)
  - From both known dates as well as user specified dates (since there may be domain-specific special events, like the start of a sports season, that aren't important dates for most domains)
- seasonality
- detrending features

We should put together a document that defines these concepts and further investigates what primitives exist in Featuretools that can be used for these purposes.

New primitives may need to be created or changes may need to be made to existing ones. This spike should determine what is necessary.

**Comment by tamargrey** [comment]
Adding the fourier transform tsfresh primitives as rolling transform primitives may be useful for time series (@freddyaboulton, @ParthivNaresh )

- https://github.com/alteryx/featuretools-tsfresh-primitives/blob/main/featuretools_tsfresh_primitives/primitives/fft_aggregated.py
- https://github.com/alteryx/featuretools-tsfresh-primitives/blob/main/featuretools_tsfresh_primitives/primitives/fft_coefficient.py

**Comment by ozzieD** [comment]
> Adding the fourier transform tsfresh primitives as rolling transform primitives may be useful for time series (@freddyaboulton, @ParthivNaresh )
> 
> * https://github.com/alteryx/featuretools-tsfresh-primitives/blob/main/featuretools_tsfresh_primitives/primitives/fft_aggregated.py
> * https://github.com/alteryx/featuretools-tsfresh-primitives/blob/main/featuretools_tsfresh_primitives/primitives/fft_coefficient.py

Done: https://github.com/alteryx/featuretools-tsfresh-primitives/pull/100
