### ISSUE TITLE
Difference between attribute of stack_on and base_of in class AggregationPrimitive

### ISSUE THREAD

**Issue by c787297017** [alteryx/featuretools#1739]
What's the difference between attribute of stack_on(stack_on_exclude) and base_of(base_of_exclude) in class AggregationPrimitive? 

I try to put a custom primitive that is for transformation into the list of stack_on_exclude or base_of_exclude in a primitive class inherited from primitive class Sum(standard primitive in featuretools), because I don't want to see the result of my custom primitive is aggregated by primitive sum, but it doesn't work.

Looking forward for your reply and many thanks for your work.

**Comment by jeff-hernandez** [comment]
@c787297017  thanks for the question! `stack_on_exclude` will exclude the given primitives as inputs, whereas `base_of_exclude` will exclude itself as an input to the given primitives. For example, if you run this code you'll get the listed feature definitions.

```python
from woodwork.column_schema import ColumnSchema
import featuretools as ft
import woodwork as ww


class Abs(ft.primitives.TransformPrimitive):
    input_types = [ColumnSchema(semantic_tags={'numeric'})]
    return_type = ColumnSchema(semantic_tags={'numeric'})
    name = 'abs'

    def get_function(self):
        return abs


class Sum(ft.primitives.AggregationPrimitive):
    input_types = [ColumnSchema(semantic_tags={'numeric'})]
    return_type = ColumnSchema(semantic_tags={'numeric'})
    name = 'sum'

    def get_function(self):
        return sum


if __name__ == '__main__':
    es = ft.demo.load_mock_customer(return_entityset=True)

    fd = ft.dfs(
        entityset=es,
        features_only=True,
        agg_primitives=[Sum],
        trans_primitives=[Abs],
        target_dataframe_name='sessions',
    )
```
```
[<Feature: customer_id>,
 <Feature: device>,
 <Feature: SUM(transactions.amount)>,
 <Feature: customers.zip_code>,
 <Feature: SUM(transactions.ABS(amount))>,
 <Feature: ABS(SUM(transactions.amount))>,
 <Feature: customers.SUM(transactions.amount)>]
```

You can avoid generating `<Feature: SUM(transactions.ABS(amount))>` by using `base_of_exclude` to exclude `Abs` from being an input to `Sum`.

```python
class Abs(ft.primitives.TransformPrimitive):
    ...
    base_of_exclude = [Sum]
```

Alternatively, you can use `stack_on_exclude` to exclude `Abs` as an input primitive.

```python

class Sum(ft.primitives.AggregationPrimitive):
    ...
    stack_on_exclude = [Abs]

```

Let me know if you found this helpful.

**Comment by c787297017** [comment]
@jeff-hernandez Thanks for your help. 

One more thing, could you help me to use the parameter **allowed_paths** in **featuretools.dfs**? I try to set it as **[[entity_a, entity_b, entity_c]]** (there are 5 entities in my entityset with single path) and confused about the result, because I got features only from entity_a and entity_b(no entity_c). Could you please generate an example like above reply? Thanks again for your help.
