### ISSUE TITLE
Use class name when parsing primitive string inputs to DFS

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1750]
Currently in Featuretools, string primitive inputs to dfs are handled by looking at the available primitives, and if a string input matches one of the primitive strings, we use that primitive class in dfs.

This problem with this is how that string matching occurs. The strings that are being matched are created in in `get_aggregation_primitives` and `get_transform_primitives` by looking at `prim.name.lower`. 

- `Primitive.name` is an attribute set in each primitive's definition, and they tend to be the lower case snake-case version of the primitive's class name. 
- So `Count` becomes `'count'` and `AddNumeric` becomes `'add_numeric'`.

Because `Primitive.name` can be any value, it means that the string with which a user can define primitive inputs to DFS is a relatively obscure attribute separate from the class name that users would need to look up to be able to use if the name were ever anything other than the expected camel case version of the class name (and I believe typos in primitive names have caused bugs before). 

We should consider using the primitive class names themselves to determine valid string inputs. [Woodwork does this with LogicalTypes](https://github.com/alteryx/woodwork/blob/main/woodwork/logical_types.py#L29), and allows both camel case and snake case versions of class names as inputs to woodwork init with its own [string to logical type converter](https://github.com/alteryx/woodwork/blob/main/woodwork/type_sys/type_system.py#L356), not caring about capitalization. Featuretools may want to adopt that behavior as well, allowing CamelCase primitive string inputs.

We can also consider changing what type of strings are allowed, to not allow different capitalizations and be more restrictive, though we may not want to cause breaking changes for this.

**Comment by gsheni** [comment]
Closing in favor of: https://github.com/alteryx/featuretools/issues/2240
