### ISSUE TITLE
Allow users to pass camelCase to DFS for primitives

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1761]
- We currently allow primitives name (as strings) to be passed to DFS. `add_numeric`
- We should modify this behavior to allow camelCase (which should match `primitive.__name__`) (`addNumeric`)
  - This is different than TitleCase (`AddNumeric`)
  - If possible, we should make it work with both. 
- Users can still pass primitive names.
- Eventually we will phase out primitive names (https://github.com/alteryx/featuretools/issues/1750)

**Comment by thehomebrewnerd** [comment]
@gsheni Was looking at this more closely. I think `primitive.__name__` returns the TitleCase version of the primitive - the string equivalent of the class name:

```>>> import featuretools as ft
>>> ft.primitives.standard.IsNull.__name__
'IsNull'
>>> ft.primitives.standard.AddNumeric.__name__
'AddNumeric'
```

**Comment by gsheni** [comment]
@thehomebrewnerd I see. Is your point that we don't store the camelCase anywhere?

**Comment by gsheni** [comment]
My opinion would be yes we do. It makes it less likely that a Featuretools user will error when using DFS.

**Comment by gsheni** [comment]
Completed in #1854
