### ISSUE TITLE
Bug with parallel chunk calculation and cutoff time df

### ISSUE THREAD

**Issue by VGODIE** [alteryx/featuretools#1763]
#### Bug Description
In my case I used dfs with cutoff time as df and n_jobs == -1
In the previous featuretools version everything worked fine. But after v.1.0.0 release I have found out that dfs breaks when running it with cutoff time which contains extra columns (pass_columns) and n_jobs > 1. The error is the following
`AttributeError: 'NoneType' object has no attribute 'logical_types'`

It happens in the following function `get_ww_types_from_features`
In the following lines
```
    if pass_columns:
        cutoff_schema = cutoff_time.ww.schema
        for column in pass_columns:
            logical_types[column] = cutoff_schema.logical_types[column]
            semantic_tags[column] = cutoff_schema.semantic_tags[column]
            origins[column] = "base"
```

However, when n_jobs == 1 everything works fine. I have investigated the source code and have found that it is probably caused by the fact that when cutoff_times is cut into chunks in the `parallel_calculate_chunks` function, the resulting chunks loose woodwork extension. 

So to solve this issue, I think, it is needed to make .ww.init() for every chunk after division

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 1.0.0

SYSTEM INFO
-----------
python: 3.7.5.final.0
python-bits: 64
OS: Darwin
OS-release: 19.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: ru_RU.UTF-8
LOCALE: ru_RU.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.21.1
pandas: 1.3.2
tqdm: 4.62.2
PyYAML: 5.4.1
cloudpickle: 1.6.0
dask: 2021.9.0
distributed: 2021.9.0
psutil: 5.8.0
pip: 19.2.3
setuptools: 41.2.0

</details>

**Comment by rwedge** [comment]
@VGODIE thanks for the report!
