### ISSUE TITLE
Remove pandas workaround in `_roll_series_with_gap`

### ISSUE THREAD

**Issue by tamargrey** [alteryx/featuretools#1771]
In #1770, a workaround had to be added for the following pandas bug https://github.com/pandas-dev/pandas/issues/43016. This bug has been fixed and will be released as a part of pandas `1.4.0` release. 

Once 1.4.0 is out and we're okay with upping our min requirement, we can remove the workaround.

**Comment by gsheni** [comment]
This will require https://github.com/alteryx/featuretools/issues/1771
