### ISSUE TITLE
Bug with parallel feature matrix calculation within sklearn cross-validation

### ISSUE THREAD

**Issue by VGODIE** [alteryx/featuretools#1778]
### Bug with parallel feature matrix calculation within sklearn cross-validation

-----
#### Bug Description

Hello, guys! Thank you for the quick release of featuretools 1.1.0 ! 

During my research I have faced the following bug:
I have an estimator which is actually an `imblearn Pipeline`. The estimator consists of several steps including my custom transformer which calculates feature matrix with `featuretools`. And I want to check the quality of the model with `sklearn cross_validate` function . If I set `n_jobs` > 1 both in `featuretools.calculate_feature_matrix` and in `sklearn.cross_validate`, then I get an unexpected error `ValueError: cannot find context for 'loky'`. When either one of `n_jobs` is set to 1, then everything works fine.

I googled for some time and I understood that such error might happen when parallelization is used without `if __name__ == '__main__'` - but it's the best information I've got - nothing more valuable. So for me it looks like there is some conflict in parallelization usage in `sklearn` and `featuretools`. And as far both of the libraries are essential as well as parallelization working with big data, i really hope you will be able to find a way to fix it :)

P.S this problem was actual before 1.0.0 release - previously I used 0.24.0 and still faced it

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 1.1.0

SYSTEM INFO
-----------
python: 3.7.5.final.0
python-bits: 64
OS: Darwin
OS-release: 19.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: ru_RU.UTF-8
LOCALE: ru_RU.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.21.1
pandas: 1.3.2
tqdm: 4.62.2
PyYAML: 5.4.1
cloudpickle: 1.6.0
dask: 2021.10.0
distributed: 2021.10.0
psutil: 5.8.0
pip: 19.2.3
setuptools: 41.2.0

</details>

**Comment by thehomebrewnerd** [comment]
@VGODIE I can try to help with this issue. Can you provide a minimal complete example that reproduces this problem, so I can try to duplicate on my end and troubleshoot?

**Comment by VGODIE** [comment]
> @VGODIE I can try to help with this issue. Can you provide a minimal complete example that reproduces this problem, so I can try to duplicate on my end and troubleshoot?

Cool ! I work on task where I create a tabular DataFrame from entities with cutoff time. As a model I use catboost but I suppose it doesn't matter. 

My custom class looks smth like that

```
class Transformer(TransformerMixin):
    def __init__(self, feature_defs):
        self.feature_defs = feature_defs
    def fit(self, X, y):
        # logic for creating entity set
        # my entityset consists of X and target dataframe
        self.es = create_es(X)
        
    def transform(self, X, y):
        X_res = featuretools.calcuate_feature_matrix(self.feature_defs, self.es, n_jobs=-1)
        return X_res
        
model = Pipeline([('tr', Transformer(feature_defs)), ('regressor', CatBoostRegressor())])

cross_validate(model, X, y, n_jobs=-1)
```

Tell me if this is enough or you need more detailed information?

**Comment by thehomebrewnerd** [comment]
@VGODIE That helps, but if you can provide a full code example that would be best. That way I don't have to guess at everything else you are doing. You don't need to provide a full dataset, especially if it isn't anything that is specific to a certain set of rows/columns.

If that isn't possible, I can try to work from this.

**Comment by VGODIE** [comment]
@thehomebrewnerd full code example would be quite complicated - I think it will only make matters worse - it contains tons of custom stuff that does not relate to this issue. Moreover, I can not share data due to the NDA. But I can help you not to guess as much as I can by answering more detailed questions that might arise. 

Besides, I suppose that it actually does not matter what data and  features to use. It is just required that features are calculated within pipeline and n_jobs>1. And this pipeline is tested with sklearn cross-validation which is also ran with n_jobs>-1 - double parallelization so to say

**Comment by gsheni** [comment]
@VGODIE can you create a reproducible example with our demo datasets? 
- https://featuretools.alteryx.com/en/latest/api_reference.html#demo-datasets
You can get an entityset or a dataframe with this:
```python
import featuretools as ft

es = ft.demo.load_retail()
assert isinstance(es, EntitySet)

df = ft.demo.load_retail(return_single_table=True)
assert isinstance(df, pd.DataFrame)
```

**Comment by VGODIE** [comment]
@gsheni Okey , I'll make it !

**Comment by VGODIE** [comment]
```
import featuretools as fts
from sklearn.base import TransformerMixin
from imblearn.pipeline import Pipeline
from catboost import CatBoostClassifier as cat
from sklearn.model_selection import cross_validate
import sklearn
import imblearn
import catboost


# featuretools version is 1.1.0
# sklearn version is 0.24.2
# imblearn version is 0.8.0
# catboost version is 0.26.1

es = fts.demo.load_retail()

df = fts.demo.load_retail(return_single_table=True)
X = df.sample(frac=0.5)
y = X['cancelled'].astype('int')
X.drop(columns='cancelled', inplace=True)

features = fts.dfs(entityset=es, target_dataframe_name='orders', features_only=True)

class Transformer(TransformerMixin):
    
    def __init__(self, features):
        self.features = features

    def fit(self, X, y):
        self.es = fts.demo.load_retail()
        return self
    
    def transform(self, X, y=None):
        X_tr = fts.calculate_feature_matrix(self.features, self.es, n_jobs=-1)
        numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
        X_final = X_tr.select_dtypes(include=numerics)
        
        return X_final
    
model = Pipeline([('tr', Transformer(features)), ('model',cat)])

# this is the error !!!

cross_validate(model, X, y, cv=5, n_jobs=-1)
```

**Comment by thehomebrewnerd** [comment]
@VGODIE Thanks for the additional detail. I will start looking into this today.

**Comment by thehomebrewnerd** [comment]
@VGODIE I was able to reproduce the issue, and I have an idea what might be going on, but I need to investigate this further before I can give you a solid solution/answer. Unfortunately, I am out of the office until Tuesday, but I will pick it back up then and get back to you with a better answer as soon as I can.

**Comment by VGODIE** [comment]
@thehomebrewnerd thank you very much for your quick response ! 
I'm looking forward to your ideas for solution !

**Comment by thehomebrewnerd** [comment]
@VGODIE I have looked into this a bit and I have a local fix working. The original issue, I believe is stemming from making nested distributed calls (one in your original `cross_validate` call and another in the featuretools `calculate_feature_matrix` call.

Basically the fix involves changing the way you call `cross_validation`, coupled with a change Featuretools so that the same Dask client gets used by sklearn and Featuretools. Will need to think about the best way to implement this fix in Featuretools, but will keep working on this.

**Comment by thehomebrewnerd** [comment]
@VGODIE I have created a branch with a change to Featuretools that should work to do what you want. If you want to test it out you can install Featuretools from this branch using the command below, or you can wait until the next release of Featuretools to test it out.

```bash
pip install git+https://github.com/alteryx/featuretools.git@sklearn-bug
``` 

Below is a modified version of your example cod that should work with the updated version of Featuretools. There are a few changes to note:
- We pass the address of an existing Dask cluster to the calculate feature matrix call to tell Featuretools to use this cluster instead of creating a new one like happens when you only specify `n_jobs`
- We update the call to `cross_validate` to use Dask instead of the default joblib
- Don't use `n_jobs` with either of the distributed calls - instead the number of workers will be determined when you create your Dask cluster

```python
import pandas as pd
import featuretools as ft

from sklearn.base import TransformerMixin
from imblearn.pipeline import Pipeline
from catboost import CatBoostClassifier as cat
from sklearn.model_selection import cross_validate


# Create a Dask client and get its address
from dask.distributed import Client
client = Client()
address = client.scheduler_info()['address']

es = ft.demo.load_retail()
features = ft.dfs(entityset=es, target_dataframe_name='orders', features_only=True)

df = ft.demo.load_retail(return_single_table=True)
X = df.sample(frac=0.5)
y = X['cancelled'].astype('int')
X.drop(columns='cancelled', inplace=True)


class Transformer(TransformerMixin):
    
    def __init__(self, features):
        self.features = features

    def fit(self, X, y):
        self.es = ft.demo.load_retail()
        return self
    
    def transform(self, X, y=None):
        dask_kwargs = {"cluster": address}  # Use the existing Dask client address
        X_tr = ft.calculate_feature_matrix(self.features, self.es, dask_kwargs=dask_kwargs)
        numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
        X_final = X_tr.select_dtypes(include=numerics)
        
        return X_final


model = Pipeline([('tr', Transformer(features)), ('model', cat)])

# Use Dask for cross_validate
import joblib
with joblib.parallel_backend('dask'):
    output = cross_validate(model, X, y, cv=5)
```

**Comment by gsheni** [comment]
@VGODIE I am closing out this issue. Let us know if you run into this problem or need further help.

**Comment by VGODIE** [comment]
Thank you very much for your help - it worked out !
