### ISSUE TITLE
Why did I get different number of features?

### ISSUE THREAD

**Issue by jingsupo** [alteryx/featuretools#1800]
```
def get_feature(target_dataframe_name):
    feature_matrix, feature_defs = ft.dfs(
        entityset=es,
        target_dataframe_name=target_dataframe_name,
        agg_primitives=[
            "sum",
            "max",
            "min",
            "mean",
            "std",
            "count",
            "num_unique",
            "percent_true",
        ],
        # trans_primitives=[],
        # where_primitives=[
        #     "sum",
        #     "max",
        #     "min",
        #     "mean",
        #     "std",
        #     "count",
        #     "num_unique",
        #     "percent_true",
        # ],
        # seed_features=[],
        max_depth=2,
    )
    return feature_matrix, feature_defs
```

I have 6 data tables:

```
tables = [
    "T07_CASE_APPLICATION_UH",
    "T07_CASE_TRANSACTION_KY_UH",
    "T47_TRANSACTION",
    "T47_PARTY",
    "T47_ID_DEPOSIT",
    "T47_INDIVIDUAL",
]
```

When I change the number of rows of the 6 data tables, the number of features generated is different, why ?

Case 1:

```
Entityset: case_scoring
  DataFrames:
    T07_CASE_APPLICATION_UH [Rows: 1000, Columns: 45]
    T07_CASE_TRANSACTION_KY_UH [Rows: 1000, Columns: 10]
    T47_TRANSACTION [Rows: 1000, Columns: 103]
    T47_PARTY [Rows: 1000, Columns: 46]
    T47_ID_DEPOSIT [Rows: 1000, Columns: 45]
    T47_INDIVIDUAL [Rows: 1000, Columns: 45]
  Relationships:
    T07_CASE_TRANSACTION_KY_UH.APPLICATION_NUM -> T07_CASE_APPLICATION_UH.APPLICATION_NUM
    T07_CASE_APPLICATION_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_TRANSACTION.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_ID_DEPOSIT.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_INDIVIDUAL.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.TRANSACTIONKEY -> T47_TRANSACTION.TRANSACTIONKEY
```

![image](https://user-images.githubusercontent.com/7351235/144794606-37647a91-07aa-4fb0-a51f-e634b2e2401a.png)

Case 2:

```
Entityset: case_scoring
  DataFrames:
    T07_CASE_APPLICATION_UH [Rows: 10000, Columns: 45]
    T07_CASE_TRANSACTION_KY_UH [Rows: 10000, Columns: 10]
    T47_TRANSACTION [Rows: 10000, Columns: 103]
    T47_PARTY [Rows: 10000, Columns: 46]
    T47_ID_DEPOSIT [Rows: 10000, Columns: 45]
    T47_INDIVIDUAL [Rows: 10000, Columns: 45]
  Relationships:
    T07_CASE_TRANSACTION_KY_UH.APPLICATION_NUM -> T07_CASE_APPLICATION_UH.APPLICATION_NUM
    T07_CASE_APPLICATION_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_TRANSACTION.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_ID_DEPOSIT.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_INDIVIDUAL.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.TRANSACTIONKEY -> T47_TRANSACTION.TRANSACTIONKEY
```

![image](https://user-images.githubusercontent.com/7351235/144794874-8ddc4306-64cd-4b48-be5f-dc6de3c2c8e9.png)

Case 3:

```
Entityset: case_scoring
  DataFrames:
    T07_CASE_APPLICATION_UH [Rows: 100000, Columns: 45]
    T07_CASE_TRANSACTION_KY_UH [Rows: 100000, Columns: 10]
    T47_TRANSACTION [Rows: 100000, Columns: 103]
    T47_PARTY [Rows: 100000, Columns: 46]
    T47_ID_DEPOSIT [Rows: 100000, Columns: 45]
    T47_INDIVIDUAL [Rows: 100000, Columns: 45]
  Relationships:
    T07_CASE_TRANSACTION_KY_UH.APPLICATION_NUM -> T07_CASE_APPLICATION_UH.APPLICATION_NUM
    T07_CASE_APPLICATION_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_TRANSACTION.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_ID_DEPOSIT.PARTY_ID -> T47_PARTY.PARTY_ID
    T47_INDIVIDUAL.PARTY_ID -> T47_PARTY.PARTY_ID
    T07_CASE_TRANSACTION_KY_UH.TRANSACTIONKEY -> T47_TRANSACTION.TRANSACTIONKEY
```

![image](https://user-images.githubusercontent.com/7351235/144795309-23c0a5f9-17e1-473e-8375-811ab1dfe557.png)

Not only the number of features is different, the features content is very different !

![image](https://user-images.githubusercontent.com/7351235/144795691-f95e1574-e6c4-4358-95c2-4682a96176e8.png)

Please help me. Why is this happening? Thank you very much.

**Comment by thehomebrewnerd** [comment]
@jingsupo What version of Featuretools are you using?

The features that get generated depend on the type of data in the column. Featuretools attempts to infer the type of the column if you do not specify it. Without knowing more detail about your dataset, my initial guess is that when you have a different number of rows present, Featuretools might be inferring different logical types for the columns in your entitysets as the values present in a column can change how things get inferred in some cases.

I would start to investigate by comparing the logical types that Featuretools has inferred for your dataframes by looking at the information returned by running `es["your_dataframe_name_here"].ww`, assuming you are using a Featuretools version greater than 1.0. If you see a difference in logical types for these columns, that would explain why you are getting different features returned.

**Comment by jingsupo** [comment]
@thehomebrewnerd Thank you for your reply, my featuretools version is 1.0.0.

I'll try your suggestion.

**Comment by jingsupo** [comment]
I run es[tables[0]].ww

Case 2:

![image](https://user-images.githubusercontent.com/7351235/144957719-8670f31a-a121-4a53-91fd-fbd432f7c646.png)

Case 3:

![image](https://user-images.githubusercontent.com/7351235/144957746-04051982-53c1-4de2-a58a-4657918a6089.png)

**Comment by thehomebrewnerd** [comment]
@jingsupo If you look at the `ACTION_DESCRIP` field for example. In Case 2, this column is being inferred as a `Datetime` logical type, but in Case 3, this is being inferred as a `Categorical` logical type. Featuretools builds different features from Datetime columns than it does for `Categorical` columns, so this would explain why you are seeing a different number of features in your different cases.

If you believe Featuretools is inferring the types incorrectly, you can specify them manually when you add the dataframe to your entityset. For example, if you want to make sure the logical type for the `ACTION_DESCRIP` column is always `Datetime`, you can specify that by passing a `logical_types` dictionary to the `add_dataframe` call, similar to this:

```python
es = ft.EntitySet()
es.add_dataframe(dataframe=your_dataframe,
                 dataframe_name="your_dataframe_name",
                 index="index_column",
                 logical_types={"ACTION_DESCRIP": "Datetime"}
)
```

I believe that if all of your logical types match between Case 2 and Case 3 you will see the same number of features generated in both cases.

If you need more information on how the column types work in Featuretools you can refer to these guides:
- [Representing Data with EntitySets](https://featuretools.alteryx.com/en/stable/getting_started/using_entitysets.html#Adding-dataframes)
- [Woodwork Typing in Featuretools](https://featuretools.alteryx.com/en/stable/getting_started/using_entitysets.html#Adding-dataframes)

Finally, if you find there is something significantly wrong with the logical types that are being inferred for your columns, please let us know and we can take a closer look.

**Comment by jingsupo** [comment]
Thank you very much. I think this should solve my problem.

**Comment by alanzhanglei** [comment]
Did you solve the problem?
