### ISSUE TITLE
Change LatLong values from NaN to tuple of NaNs during EntitySet creation

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1819]
- To give LatLong a consistent NaN representation and make for fast primitive calculations, we should use the tuple of NaN
- This means that during the EntitySet creation process, any single np.nan values should be changed to (np.nan, np.nan)
- Woodwork will allow for both NaN representations (np.nan & tuple(np.nan, np.nan))
  - https://github.com/alteryx/woodwork/issues/1226

**Comment by dvreed77** [comment]
The koalas dependency to WW < 0.12.0 makes this challenging. EntitySets with dataframes that have normalized LatLong columns (ie. NaN converted to [NaN, NaN]) that are deserialized from CSV create issues during Woodwork initialization.

There are potential workarounds but these would create koalas specific codepaths and would be easier to wait until Koalas dataframes cans support WW >= 0.12.0.

**Comment by gsheni** [comment]
@dvreed77 that sounds good to me. Let's wait until Woodwork supports the latest Koalas.
