### ISSUE TITLE
SPIKE - Workflow for adding and removing primitives

### ISSUE THREAD

**Issue by kmax12** [alteryx/featuretools#182]
A common workflow in Featuretools is to add and remove primitives to find an optimal set. See this StackOverflow [answer](https://stackoverflow.com/questions/50527392/how-to-decide-which-primitives-to-use-for-dfs) for more details.

As a user iterates through primitive options, they have to rerun `ft.dfs` with the different inputs. This means the feature calculations are often repeated. To improve the time it takes to do this workflow, I propose that a user optionally be able to provide a feature matrix from a previous run of DFS. If a feature for a new run already exists from a prior run, it wont be recalculated. 

For example

```
# Normal DFS call
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=["count"],
                                      trans_primitives=["month"])
```

Then a user adds a new primitive. This should only calculate the new features
```
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=["count", "sum"],
                                      trans_primitives=["month"],
                                      feature_matrix=feature_matrix)
```

Finally, the user decides that the month primitive is not needed. This change will not trigger any recalculation because we are only removing features

```
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers",
                                      agg_primitives=["count", "sum"],
                                      trans_primitives=[],
                                      feature_matrix=feature_matrix)
```

If a user removed the `feature_matrix` argument from any of the above calls the return values would not change.

**Comment by dlionbox** [comment]
Is this working right now? Or it will be developed?
It will be very usefull.

**Comment by kmax12** [comment]
@dlionbox it isn't implemented at the moment as we're not sure how much people want it. if more people chime in that they want it, we'd be happy to build it!

**Comment by dlionbox** [comment]
@kmax12 thank you for answering! I'll be happy using it
