### ISSUE TITLE
Split Transform Primitives out into separate files

### ISSUE THREAD

**Issue by dvreed77** [alteryx/featuretools#1855]
- `transform_primitive.py` is becoming very large. I suggest splitting out into separate files. 
- We could split this file up by groups (such as LatLong transform primitives in 1 file).

**Comment by jacobboney** [comment]
Hello Mr. Reed, I'm a computer science student currently taking a class in software engineering. An assignment we have is to contribute to an open source project. I was hoping that I would be able to assist you with the refactoring. I may need a little guidance to begin as this would be my first contribution, but I do have experience with python. 

Thank you

**Comment by gsheni** [comment]
Hi @jacobboney, feel free to put up a PR and we can give you feedback. There is instructions on how to contribute here:
- https://github.com/alteryx/featuretools/blob/main/contributing.md

**Comment by jacobboney** [comment]
Great! Thanks for the swift response.

**Comment by dvreed77** [comment]
Yes, would very much appreciate the help @jacobboney

**Comment by Anku5hk** [comment]
@jacobboney are you working on this?

**Comment by dvreed77** [comment]
@Anku5hk This is closed now. Thanks for bringing it to our attention
