### ISSUE TITLE
Update koalas code to pyspark pandas API instead in Featuretools

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/featuretools#1864]
The koalas library is now in maintenance mode only, and the core code has been integrated into pyspark, starting with version 3.2. We should update our koalas specific code to use the new pyspark pandas API: https://spark.apache.org/docs/latest/api/python/getting_started/quickstart_ps.html

**Comment by tamargrey** [comment]
As part of #1865, we pinned the pandas requirement in `koalas-requirements.txt` below 1.4.0, so hopefully updating to the new api supports pandas 1.4.0 and greater
