### ISSUE TITLE
Custom primitives can not be pickled

### ISSUE THREAD

**Issue by tvdboom** [alteryx/featuretools#1942]
[A clear and concise description of what the bug is.]

Hi, I have built a custom transformer for a sklearn pipeline. In the transformer, dfs transforms a provided dataset using existing primitives (e.g. `add_numeric`) but also custom ones created with the snippet showed below. The code works fine, but when I try to pickle the transformer, I get the following error for the custom primitives:

`_pickle.PicklingError: Can't pickle <class 'featuretools.primitives.base.transform_primitive_base.cos'>: it's not found as featuretools.primitives.base.transform_primitive_base.cos`

I understand the error, but don't know how to solve it. I tried this hacky solution, which allows me to pickle the object but not to unpickle it.

```python
from featuretools.primitives.base import transform_primitive_base

setattr(transform_primitive_base, "cos", custom_primitive)
```

Any help is appreciated.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
custom_primitive = ft.primitives.make_trans_primitive(
    function=lambda x: np.cos(x),
    input_types=[ColumnSchema()],
    return_type=ColumnSchema(semantic_tags=["numeric"]),
    name="cos",
)

```

#### Output of ``featuretools.show_info()``

<details>

[paste the output of ``featuretools.show_info()`` here below this line]

Featuretools version: 1.6.0
Featuretools installation directory: C:\Users\Mavs\Documents\Python\ATOM\venv310\lib\site-packages\featuretools
SYSTEM INFO
-----------
python: 3.10.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None
INSTALLED VERSIONS
------------------
numpy: 1.21.5
pandas: 1.4.1
tqdm: 4.63.0
cloudpickle: 2.0.0
dask: 2022.1.1
distributed: 2022.1.1
psutil: 5.9.0
pip: 22.0.3
setuptools: 57.0.0

</details>

**Comment by tamargrey** [comment]
@tvdboom You should be able to pickle a custom primitive if you define the class yourself. So, in this case, something like:

```python
class CustomPrimitive(TransformPrimitive):
    name = "cos"
    input_types = [ColumnSchema(semantic_tags=["numeric"])]
    return_type = ColumnSchema(semantic_tags=["numeric"])

    def get_function(self):
        return lambda x: np.cos(x)
```

**Comment by tvdboom** [comment]
@tamargrey I added the desired primitives to featuretools' codebase so that I can use them without custom classes after next release. In the mean time, I'll use a class like you suggest. thanks for the tip.
