### ISSUE TITLE
Add Sine, Cosine, Tangent, SquareRoot, Log primitives

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1943]
- We can add primitives that calculate the since, cosine, and tangent of a numeric column
- Let's make sure we do this in a fast way
- An example how another library that uses Featuretools does it:
  - https://github.com/tvdboom/ATOM/blob/7a5ac34b43de1c72cdb22eb6cae60462da75a77c/atom/feature_engineering.py#L379

**Comment by tvdboom** [comment]
It would be nice to also have the square root (`np.sqrt`) and logarithm (`np.log`). They can be implemented in a similar way.

**Comment by gsheni** [comment]
@tvdboom Sounds good!

**Comment by tvdboom** [comment]
I can try and create a PR for this myself if that's oke. Should be pretty straight forward

**Comment by gsheni** [comment]
@tvdboom sure that sounds good.

**Comment by tvdboom** [comment]
#1948
