### ISSUE TITLE
Upgrade pandas >= 1.4.0

### ISSUE THREAD

**Issue by jeff-hernandez** [alteryx/featuretools#1951]
Pandas 1.4.0 introduces breaking changes. We should make the necessary updates to support the latest pandas version.

**Comment by rohan-gt** [comment]
Any update on this?

**Comment by gsheni** [comment]
@rohan-gt We now support pandas >=1.4.0 (we accidentally forgot to close this issue on Apr , sorry!).

Featuretools >=1.8.0 supports pandas 1.4.0

**Comment by rohan-gt** [comment]
@gsheni I'm getting a dependency issue error when I'm installing featuretools with pandas >=1.4.0. Can you check the requirements and confirm?

**Comment by gsheni** [comment]
@rohan-gt what is the error you are getting?
The `pip install pandas==1.4.0 featuretools` works for me (in Python 3.8.11)
```
~ ❯ pip list | grep featuretools                                                                                                                               27s   3.8.11
featuretools          1.11.1
~ ❯ pip list | grep pandas                                                                                                                                           3.8.11
pandas                1.4.0
```

**Comment by rohan-gt** [comment]
Forgot to mention I was using poetry to install

**Comment by gsheni** [comment]
@rohan-gt Can you share with the poetry command you are using to install? And the error message you are getting?

**Comment by rohan-gt** [comment]
I add the following line under `[tool.poetry.dependencies]`:
`featuretools = {version = "^1.11.1", extras = ["complete"]}`

and then ran `poetry update`

**Comment by thehomebrewnerd** [comment]
@rohan-gt The `"complete"` install of Featuretools was not compatible with pandas `>=1.4.0` prior to the latest release. I think if you use version `1.12.0` instead of `1.11.1` this should resolve your dependency conflict. 

I'm not too familiar with poetry, so I'm still testing this out a little on my end to confirm.

If you are still getting a dependency error with Featuretools 1.12.0, can you please post the entire error message to help us debug further.

**Comment by thehomebrewnerd** [comment]
@rohan-gt Based on my testing Featuretools version 1.12.0 is fully compatible with pandas 1.4.3, including the complete install of Featuretools. I am going to close this issue, but if you are still having problem, feel free to comment here and we can reopen and investigate further.
