### ISSUE TITLE
How to restrict operations between two fields

### ISSUE THREAD

**Issue by jingsupo** [alteryx/featuretools#1966]
I have four fields ['a', 'b', 'c', 'd']. How can I do the following with featuretools:

1. Generate a new feature, and the feature value is the ratio between two of the above fields;

2. The division between 'b' and 'd' is not allowed to generate new features, and the others can be used.

Thank you very much!

**Comment by rwedge** [comment]
Hi @jingsupo,

1.  Would the DivideNumeric primitive work for this?
2.  While not perfect, you could use drop_contains to filter out features that use "b / d": `drop_contains=["(b / d", ".b / d"]`

**Comment by jingsupo** [comment]
![image](https://user-images.githubusercontent.com/7351235/158920623-40a97efa-bd0e-48d3-8c16-05ba9d9c5d6b.png)
Thank you. Both can work, but they will generate unwanted features "b / d".

**Comment by rwedge** [comment]
I'll close in favor of #1968, then
