### ISSUE TITLE
How can i generate such a feature: column1 / column2

### ISSUE THREAD

**Issue by jingsupo** [alteryx/featuretools#1968]
Hello! Suppose I want to generate such a feature: amount / product_id (just suppose), how can I do?

My entityset is like this:
![image](https://user-images.githubusercontent.com/7351235/158772635-fddaddf7-bc45-47d5-993e-6e414ddb52a8.png)
![image](https://user-images.githubusercontent.com/7351235/158772733-33efcf41-0b60-4420-bcb9-e23bfa8ee634.png)

My code is here:
![image](https://user-images.githubusercontent.com/7351235/158773531-5978c556-a068-4791-9bf9-28db343be56b.png)

`feature = get_feature("transactions", features_only=False)`

My output:

`[<Feature: session_id>,
 <Feature: product_id>,
 <Feature: amount>,
 <Feature: customer_id>,
 <Feature: cid_hour>,
 <Feature: sessions.device>,
 <Feature: sessions.customer_id>,
 <Feature: cid_hour.customer_id>,
 <Feature: sessions.COUNT(transactions)>,
 <Feature: sessions.MAX(transactions.amount)>,
 <Feature: sessions.MAX(transactions.customer_id)>,
 <Feature: sessions.MEAN(transactions.amount)>,
 <Feature: sessions.MEAN(transactions.customer_id)>,
 <Feature: sessions.MIN(transactions.amount)>,
 <Feature: sessions.MIN(transactions.customer_id)>,
 <Feature: sessions.MODE(transactions.cid_hour)>,
 <Feature: sessions.MODE(transactions.product_id)>,
 <Feature: sessions.NUM_UNIQUE(transactions.cid_hour)>,
 <Feature: sessions.NUM_UNIQUE(transactions.product_id)>,
 <Feature: sessions.SKEW(transactions.amount)>,
 <Feature: sessions.SKEW(transactions.customer_id)>,
 <Feature: sessions.STD(transactions.amount)>,
 <Feature: sessions.STD(transactions.customer_id)>,
 <Feature: sessions.SUM(transactions.amount)>,
 <Feature: sessions.customers.zip_code>,
 <Feature: cid_hour.COUNT(transactions)>,
 <Feature: cid_hour.MAX(transactions.amount)>,
 <Feature: cid_hour.MAX(transactions.customer_id)>,
 <Feature: cid_hour.MEAN(transactions.amount)>,
 <Feature: cid_hour.MEAN(transactions.customer_id)>,
 <Feature: cid_hour.MIN(transactions.amount)>,
 <Feature: cid_hour.MIN(transactions.customer_id)>,
 <Feature: cid_hour.MODE(transactions.product_id)>,
 <Feature: cid_hour.NUM_UNIQUE(transactions.product_id)>,
 <Feature: cid_hour.SKEW(transactions.amount)>,
 <Feature: cid_hour.SKEW(transactions.customer_id)>,
 <Feature: cid_hour.STD(transactions.amount)>,
 <Feature: cid_hour.STD(transactions.customer_id)>,
 <Feature: cid_hour.SUM(transactions.amount)>,
 <Feature: cid_hour.customers.zip_code>]`

There are no desired features in the output :(

**Comment by thehomebrewnerd** [comment]
@jingsupo Have you confirmed that both columns are actually typed as numeric columns? The divide numeric primitive will only work between columns that are a numeric logical type (integer, double). If your `product_id` column is a categorical column Featuretools will not recognize this as a valid input to the divide numeric primitive.

You can check your column logical types by running `es["transactions"].ww`. If the`product_id` is being inferred as a categorical column, and you want to force it to be a numeric column, you can change the type of the column by running `es["transactions"].ww.set_types(logical_types={"product_id": "Integer"})` before running DFS, or you can specify the types with the `logical_types` parameter when adding the transactions dataframe to the EntitySet.

Have a look at the documentation here for more information:
https://featuretools.alteryx.com/en/stable/getting_started/woodwork_types.html
https://featuretools.alteryx.com/en/stable/getting_started/using_entitysets.html#Adding-dataframes

If this is not your issue, please let me know and I will take a closer look.

**Comment by jingsupo** [comment]
@thehomebrewnerd Thank you, product_id column is a categorical column, this is my issue. :)

**Comment by thehomebrewnerd** [comment]
@jingsupo Glad that resolved your issue!
