### ISSUE TITLE
Rename `get_feature_names` to `get_column_names`

### ISSUE THREAD

**Issue by dvreed77** [alteryx/featuretools#1972]
As a developer, using a `get_column_names` call seems to align better with intended use of this method. A single feature can have multiple outputs that are realized as multiple columns.

#### Code Example

```python
column_names = feat.get_column_names()
```

**Comment by kushal-gopal** [comment]
If this feature needs to be implemented, I can do PR on this.

**Comment by thehomebrewnerd** [comment]
If we do decide to do this, based on recent conversations, my suggestion would be to add the new method and add a deprecation warning to the current method instead of renaming the current method in order to avoid making a breaking API change right away.

**Comment by gsheni** [comment]
I would rather have 2 functions that return the same thing, than deprecate a function we have had for a long time. 

Technically, features is an more accurate identifier.

**Comment by kushal-gopal** [comment]
Alright, this makes more sense. So now should I just create a new function which does the same thing? What shall the function name be?\
