### ISSUE TITLE
featuretools==1.3.0 and error 'ModuleNotFoundError: No module named 'woodwork.serialize''

### ISSUE THREAD

**Issue by sepidehhosseinzadeh** [alteryx/featuretools#2043]
While installing ft, it tries to 'from woodwork.serialize import typing_info_to_dict'.
Error: ModuleNotFoundError: No module named 'woodwork.serialize'

I cannot install using 'pip install https://github.com/alteryx/featuretools/archive/woodwork-integration.zip', because I can only pip install from Pypi. [As suggested here: https://featuretools.alteryx.com/en/woodwork-integration/resources/transition_to_ft_v1.0.html]

Thanks for your help.

**Comment by rwedge** [comment]
Hi @sepidehhosseinzadeh ,

You probably have a newer version of the woodwork library that doesn't work with featuretools 1.3.0.

If you want to keep using featuretools 1.3.0, you'll need to downgrade woodwork to 0.13.0 

`pip install woodwork==0.13.0`

Or you could update featuretools to the latest version

**Comment by sepidehhosseinzadeh** [comment]
Thanks for your reply, latest version 1.9.0 also has the same error.

**Comment by rwedge** [comment]
@sepidehhosseinzadeh I did not get the error when upgrading from 1.3 to 1.9 or when installing 1.9 in a fresh environment

Is it possible the upgrade was applied to the wrong environment?

**Comment by sepidehhosseinzadeh** [comment]
I am sure it's the same environment -- not upgrading though, I'm installing ft version 1.9.0, the same error happens.

**Comment by rwedge** [comment]
can you share more of the error output?

**Comment by sepidehhosseinzadeh** [comment]
/opt/conda/lib/python3.7/site-packages/featuretools/entityset/serialize.py
 import tempfile
---> 7 from woodwork.serialize import typing_info_to_dict
from featuretools.utils.gen_utils import import_or_none
---> ModuleNotFoundError: No module named 'woodwork.serialize'

**Comment by sepidehhosseinzadeh** [comment]
I added `pip install woodwork==0.13.0` after featuretool installation as well, same error.

**Comment by rwedge** [comment]
That looks like older featuretools code, `from woodwork.serialize import` isn't present in the featuretools 1.9.0 code base

It may be more convenient to help debug this using slack.  [Link to join featuretools slack](https://join.slack.com/t/alteryx-oss/shared_invite/zt-6inxevps-RSbpr9lsACE1kObXz4rIuA)

It looks like you have conda installed.  Are you able to create a new conda environment and try installing featuretools there?

**Comment by sepidehhosseinzadeh** [comment]
The link doesn't work.

**Comment by rwedge** [comment]
Try this one

https://join.slack.com/t/alteryx-oss/shared_invite/zt-182tyvuxv-NzIn6eiCEf8TBziuKp0bNA
