### ISSUE TITLE
Create design doc for single table DFS

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#2132]
- As a user of Featuretools, I want to run DFS with a single DataFrame (without having to create my EntitySet).
- For this issue, let's create a design doc that goes over how we would add this feature to DFS 
- Some initial thoughts here:
  - https://github.com/alteryx/featuretools/issues/1000

**Comment by sbadithe** [comment]
It looks like the FAQ document already has an entry on how to use DFS with a single table. In the example, it covers creating an EntitySet of one dataframe and passing it to DFS. Should I add a note explaining a dictionary can be passed in too?

**Comment by gsheni** [comment]
@sbadithe Yes, let's update the FAQ to point out 2 different options that users can do for single table. We can have the first option be without creating an EntitySet.
We should also point out the limitation of single table DFS, such as 
- No aggregation features will be generated
- Will not allow for the generation of complex features with feature stacking
- No guarantee can be made about preventing label leakage

@rwedge @thehomebrewnerd can provide more information on the limitations.
