### ISSUE TITLE
Add unit test to enforce primitive descriptions

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#2199]
- We want our primitive descriptions to be consistent and easy to understand.
- In order to do this, we can add the following test (for all primitives)
```python
docstring = primitive.__doc__
short_description = docstring.splitlines()[0]
first_word = short_description.split(' ', 1)[0]
valid_verbs = ['Calculates', 'Determines', 'Transforms', 'Computes',
                         'Shifts', 'Extracts', 'Applies']
assert any(s in first_word for s in valid_verbs)
```
- We can add more valid verbs if they are good verbs

**Comment by sbadithe** [comment]
Should failing primitive descriptions be adjusted in this PR as well?

**Comment by gsheni** [comment]
@sbadithe Yes
