### ISSUE TITLE
Error "attributeerror 'float' object has no attribute 'shape' corr" while trying 'remove_highly_correlated_features'

### ISSUE THREAD

**Issue by ziviland** [alteryx/featuretools#2229]
First, I encode Categorical features with `ft.encode_features`. After that I have are a lot of Boolean values in feature matrix. Then I'm trying to remove highly correlated features from my feature matrix with `ft.remove_highly_correlated_features`. That's where Error occurs. 

It seems that this is bug with numpy.corr method processing on Boolean values, it can't convert them to 'float64'. The solution [is here](https://stackoverflow.com/questions/40453337/python-cannot-make-corr-work). In my code I copied `remove_highly_correlated_features`function to my code and rewrote this part:

`if abs(more_complex_col.astype('float64').corr(less_complex_col.astype('float64'))) >= pct_corr_threshold:`

and it works!

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import featuretools as ft
from featuretools import selection
from featuretools.demo.flight import load_flight

es = load_flight(nrows=50)
features = ft.dfs(
    entityset=es,
    target_dataframe_name="trip_logs",
    trans_primitives=[],
    agg_primitives=[],
    max_depth=2,
    features_only=True,
)
# leave only few categorical features
features = [features[15]] + [features[21]]
feature_matrix = ft.calculate_feature_matrix(features=features, entityset=es)
# encode featues
feature_matrix, features = ft.encode_features(feature_matrix=feature_matrix, features=features)
# catch Error
selection.remove_highly_correlated_features(feature_matrix=feature_matrix, features=features)
```

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 1.12.0
Featuretools installation directory: /Users/ziviland/opt/miniconda3/envs/feeature_gen/lib/python3.10/site-packages/featuretools

SYSTEM INFO
-----------
python: 3.10.5.final.0
python-bits: 64
OS: Darwin
OS-release: 21.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.22.1
pandas: 1.3.5
tqdm: 4.64.0
cloudpickle: 2.1.0
dask: 2022.6.1
distributed: 2022.6.1
psutil: 5.9.1
pip: 21.2.4
setuptools: 61.2.0

</details>

**Comment by tamargrey** [comment]
@ziviland Thanks for the bug report. Put up a fix: https://github.com/alteryx/featuretools/pull/2231.
