### ISSUE TITLE
Fix docs build error

### ISSUE THREAD

**Issue by sbadithe** [alteryx/featuretools#2341]
Featuretools docs are not building. The error message is `TypeError: 'module' object is not callable`.

**Comment by thehomebrewnerd** [comment]
Related StackOverflow Issue: https://stackoverflow.com/questions/73372315/autosummary-fails-to-import-the-methods-from-the-package-classes-locally

The issue appears to be related to having Featuretools installed locally in editable mode. If you uninstall Featuretools with `pip uninstall featuretools` and then reinstall Featuretools in non-editable mode with `pip install .` the docs build works fine.
