### ISSUE TITLE
[refactor] PerformanceWarning: DataFrame is highly fragmented during DFS

### ISSUE THREAD

**Issue by mqtt-halogenki** [alteryx/featuretools#2405]
During the Deep Feature Synthesis python outputs the following warning:
> python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py:819: **PerformanceWarning:** DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  return data.assign(**new_cols)
```
#### Code Sample, a copy-pastable example to reproduce your bug.

```python
es = ft.EntitySet("test_data")

es.entity_from_dataframe(dataframe=test_df, entity_id = "test_", index = "id")

# Run deep feature synthesis with transformation primitives
feature_matrix, feature_defs = ft.dfs(entityset = es,
                                      trans_primitives = ['add_numeric', 'multiply_numeric']
                                     ,target_entity="test_"
                                     )

```

#### Output of ``featuretools.show_info()``

<details>

Featuretools version: 0.27.1

SYSTEM INFO
-----------
python: 3.9.15.final.0
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.UTF-8

INSTALLED VERSIONS
------------------
numpy: 1.23.4
pandas: 1.4.2
tqdm: 4.64.1
PyYAML: 6.0
cloudpickle: 2.0.0
dask: 2022.12.0
distributed: 2022.12.0
psutil: 5.9.0
pip: 22.2.2
setuptools: 65.5.0

</details>

**Comment by dvreed77** [comment]
Related to https://github.com/alteryx/featuretools/issues/2370 and https://github.com/alteryx/featuretools/issues/1698
