### ISSUE TITLE
Integration with SQL?

### ISSUE THREAD

**Issue by kmatusz** [alteryx/featuretools#248]
### Feature Request Description
The concept of EntitySet is similar to SQL database, with relations as foreign keys and entities as tables. I think a good feature would be to connect featuretools directly to an SQL database, or at least provide conversion of  a database to EntitySet automatically.

**Comment by kmax12** [comment]
@kmatusz this makes a lot of sense and is something on our list to add to Featuretools. One approach could be to use SQLAlchemy to implement this. 

If you (or anyone else reading this) is interested in contributing this functionality to Featuretools, please let us know so we can discuss further.

**Comment by jkgenser** [comment]
@kmax12 I would be very interested help with contributing this functionality to featuretools.

**Comment by gsheni** [comment]
@kmatusz Please checkout our add-on library which allows you to create EntitySets from a database:
- https://github.com/alteryx/featuretools-sql
