### ISSUE TITLE
Add Python 3.11 support and unit tests

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#2553]

**Comment by thehomebrewnerd** [comment]
I think at least two more things need to happen before we can complete this:
1. Woodwork must release a new version that removes the upper bound restriction on pyspark so we can install pyspark 3.4.0 which is required for Python 3.11.
2. numba must release version 0.57 to add Python 3.11 support

**Comment by vishalovercome** [comment]
Any timeline for this? My company has to upgrade our Spark clusters soon
