### ISSUE TITLE
ModuleNotFoundError: No module named 'featuretools.variable_types'

### ISSUE THREAD

**Issue by rcshetty3** [alteryx/featuretools#2579]
[A clear and concise description of what the bug is.]

I'm not able to run my code because of this error.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
# Your code here
import pandas as pd
#import autosklearn.classification
import featuretools as ft
from featuretools.primitives import *
from featuretools.variable_types import Numeric
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

# Input data files are available in the "../input/" directory.
import os
print(os.listdir("../input"))
```

#### Output of ``featuretools.show_info()``

<details>

[paste the output of ``featuretools.show_info()`` here below this line]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-13-b5ccf74f49bc>](https://localhost:8080/#) in <cell line: 5>()
      3 import featuretools as ft
      4 from featuretools.primitives import *
----> 5 from featuretools.variable_types import Numeric
      6 from sklearn.svm import LinearSVC
      7 from sklearn.feature_selection import SelectFromModel

ModuleNotFoundError: No module named 'featuretools.variable_types'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
</details>

**Comment by aaditya761** [comment]
In version 1:

1. The legacy Featuretools custom typing system has been replaced with Woodwork for managing column types
2. Both the Entity and Variable classes have been removed from Featuretools
3. Several key Featuretools methods have been moved or updated

Please refer to:

https://github.com/alteryx/featuretools/blob/main/docs/source/resources/transition_to_ft_v1.0.ipynb
