### ISSUE TITLE
Featuretools trying to import private scipy function float_factorial

### ISSUE THREAD

**Issue by lhoch5813** [alteryx/featuretools#2669]
Importing featuretools throws an import error due to trying to import `'float_factorial' from 'scipy._lib._util'.`, which I believe is private. I've included a screenshot of the traceback for the error. Occurring on featuretools 1.28 and scipy 1.10.1.

![](https://i.stack.imgur.com/aFF9F.png)

**Comment by tamargrey** [comment]
@lhoch5813 That import is not coming from a featuretools file. Rather, our call in our `num_peaks.py` file to `from scipy.signal import find_peaks` eventually reaches the import you mention, which is internal to scipy. I'm guessing there may be issues with how your dependencies are installed.

**Comment by thehomebrewnerd** [comment]
Closing this issue as it doesn't seem to be a Featuretools issue. Please feel free to reopen if the problem persists.
