### ISSUE TITLE
DFS stacks transform primitives in an incomplete manner

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#39]
When creating transform features on an entity, DFS applies transform primitives to the entity's identity features to create new features. At this step, DFS could either use these new features as inputs for more transform features (up to max_depth or some other arbitrary depth) or stop making transform features.

Currently, DFS stacks transform features on top of each other, but only if the transform primitive being stacked on comes before the other in the` trans_primitives` list. So if `trans_primitives=[Absolute, Percentile]`, DFS will only stack `Percentile` on `Absolute`, creating a `Percentile(Absolute(base_feature))` feature, but if `trans_primitives=[Percentile, Absolute]`, DFS will only stack `Absolute` on `Percentile`, creating a `Absolute(Percentile(base_feature))` feature.

We should decide if we want transform features to stack like this.

**Comment by Seth-Rothschild** [comment]
I think it's reasonable to have them stack in either direction as opposed to not stacking at all. There are generically there are lots of reasons to want to compose two functions.

The downside would be the risk of stacking something in a way that's strictly not useful (e.g. the absolute value of something positive). That being said, even if there are more useless stacked `trans_primitives` than useful ones, it still seems easier to ignore bad ones than to build all of the good ones as seed features.

**Comment by rwedge** [comment]
Resolved by #1119
