### ISSUE TITLE
Stacking of "where" features

### ISSUE THREAD

**Issue by nutle** [alteryx/featuretools#528]
Assume we define "interesting values" for two variables in the same entity, say, ``x``and ``y``. By defining rules for ``where_primitives``, ``dfs`` generates various aggregates with ``WHERE x = x`` and ``WHERE y = y``. However, it would be very useful to stack those variables together, so that the final result would be ``WHERE x = x and y = y``. 

Or is this possible and I'm just missing it? [The documentation didn't mention anything like that](https://docs.featuretools.com/guides/tuning_dfs.html#add-interesting-values-to-variables), and playing with ``max_depth``, obviously, didn't change anything.

**Comment by kmax12** [comment]
There is no way to automatically stack where features, but here is an approach that could work: https://stackoverflow.com/questions/54136115/how-to-create-interesting-values-using-value-combinations-from-multiple-features

**Comment by nutle** [comment]
@kmax12 Thanks for the link! Yes, this should work.

**Comment by gsheni** [comment]
@nutle closing this issue. feel free to reopen
