### ISSUE TITLE
Categorical attributes return as column of type object in feature matrix

### ISSUE THREAD

**Issue by m-knecht** [alteryx/featuretools#678]
### Feature Request Title
Categorical attributes return as columns of type object in the feature matrix 

#### Feature Request Description

Categorical attributes return as columns of type object in the feature matrix for primitives like LAST or MODE. This increases memory usage of feature matrix significantly.

Minimal working example:

```
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
print(es['sessions'])
fm, feat_defs = ft.dfs(entityset=es,target_entity="customers")
print(fm['MODE(sessions.device)'])
```

#### Expected Output

Feature matrix with columns of type category with levels as in the entity set.

#### Output of ``featuretools.show_info()``

No output generated

**Comment by gsheni** [comment]
```pyhon
# current behavior
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
fm, feat_defs = ft.dfs(entityset=es,target_entity="customers")
print(fm['MODE(sessions.device)'])

# expected behavior
import pandas as pd
pd.Series(fm['MODE(sessions.device)'], dtype="category")
```

**Comment by gsheni** [comment]
@m-knecht this issue has been resolved in the latest version of Featuretools.
