### ISSUE TITLE
When calculating direct features use default value if parent missing

### ISSUE THREAD

**Issue by CJStadler** [alteryx/featuretools#682]
For example, if there is a relationship `transaction.session_id -> sessions.id` and we are calculating a feature `transactions: sessions.SUM(transactions.value)` any rows for which there is no corresponding session should be given the default value of `0` instead of `NaN`.

Of course this should not normally occur, but when it does it seems more reasonable to use the `default_value`.

`DirectFeature.default_value` is already implemented. We should be able to use the same logic that we do for aggregation features.
https://github.com/Featuretools/featuretools/blob/6f4ffd7ef7ea42f95dbaf3892615717a521299db/featuretools/computational_backends/feature_set_calculator.py#L611-L618

**Comment by iaroslav0** [comment]
Is there any sample codes that reproduces this problem? I would like to confirm my understanding of this problem. 

For example, if transactions.value is [1,2,3,4,float('nan')], SUM(transactions.value) should be 10.0 (ignoring nan). Am I correct?

**Comment by kmax12** [comment]
Here is code that reproduces

```
import pandas as pd
import featuretools as ft
from featuretools.primitives import Sum

transactions = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "session_id": ["a", "a", "b", "c"],
    "value": [1, 1, 1, 1]
})

sessions = pd.DataFrame({
    "id": ["a", "b"]
})

es = ft.EntitySet()
es.entity_from_dataframe(entity_id="transactions",
                         dataframe=transactions,
                         index="id")
es.entity_from_dataframe(entity_id="sessions",
                         dataframe=sessions,
                         index="id")

es.add_relationship(ft.Relationship(es["sessions"]["id"], es["transactions"]["session_id"]))
es

sum_features = ft.Feature(es["transactions"]["value"], parent_entity=es["sessions"], primitive=Sum)
sessions_sum = ft.Feature(sum_features, entity=es["transactions"])

fm = ft.calculate_feature_matrix(features=[sessions_sum], entityset=es)
fm
```

the output of fm is 

```
    sessions.SUM(transactions.value)
id                                  
1                                2.0
2                                2.0
3                                1.0
4                                NaN
```

id 4 should be `0`

**Comment by seriallazer** [comment]
If no one is working on this, may I take this up?

**Comment by rwedge** [comment]
@seriallazer sure!

**Comment by seriallazer** [comment]
I've created a pull-request for the change: https://github.com/FeatureLabs/featuretools/pull/1217.
Can someone please review the changes.
Thanks!
