### ISSUE TITLE
Change make_index value for demo/flight.py example of secondary_time_index

### ISSUE THREAD

**Issue by angela97lin** [alteryx/featuretools#742]
In demo/flight.py, the following in `make_es(data)` will throw a `RuntimeError: Cannot make index: index variable already present` error because the column already exists.

`es.entity_from_dataframe('trip_logs',
                             data,
                             index='trip_log_id',
                             make_index=True,
                             time_index='date_scheduled',
                             secondary_time_index={'arr_time': arr_time_columns},
                             )`

`make_index=True` should be replaced with `make_index=False` here and in the documentation on "Handling Time"

**Comment by kmax12** [comment]
let's review if this is actually still an issue

**Comment by thehomebrewnerd** [comment]
Tested this out and there is no error when running `ft.demo.load_flight()` which calls the referenced `make_es` function. 
```
>>> import featuretools as ft
>>> es = ft.demo.load_flight()
Downloading data ...
>>> es
Entityset: Flight Data
  DataFrames:
    trip_logs [Rows: 860457, Columns: 21]
    flights [Rows: 50557, Columns: 9]
    airlines [Rows: 12, Columns: 1]
    airports [Rows: 299, Columns: 3]
  Relationships:
    trip_logs.flight_id -> flights.flight_id
    flights.carrier -> airlines.carrier
    flights.dest -> airports.dest
```

This also appears to be working properly in the documentation: https://featuretools.alteryx.com/en/stable/getting_started/handling_time.html#Secondary-Time-Index

Closing as it seems to no longer be an issue.
